from collections import defaultdict
from itertools import permutations

from comde.utils.common.natural_languages.lang_representation import SkillRepresentation

# NOTE: """order matters""". it mapped to one-hot representation.
main_texts = [
	"box",
	"puck",
	"handle",
	"drawer",
	"button",
	"lever",
	"door",
	"stick",
]
texts_variations = {
	"box": ["close the box"],
	"puck": ["slide the puck into the goal"],
	"handle": ["manipulate the handle"],
	"drawer": ["close the drawer"],
	"button": ["press the button"],
	"lever": ["pull up lever"],
	"door": ["open the door"],
	"stick": ["insert the stick"]
}

skill_infos = defaultdict(list)

for idx, (key, variations) in enumerate(texts_variations.items()):
	for text in variations:
		skill_rep = SkillRepresentation(
			title=key,
			variation=text,
			vec="override this using language model",
			index=idx
		)
		skill_infos[key].append(skill_rep)

SEQUENTIAL_REQUIREMENTS = ["sequential", "reverse"]
for (a, b) in list(permutations(range(8), 2)):
	SEQUENTIAL_REQUIREMENTS.append(f"replace {a} with {b}")

POSSIBLE_SPEEDS = {
	1: {"default": 25.0, "non_default": {"normal": 10.0, "slow": 1.5}},
	3: {"default": 25.0, "non_default": {"normal": 13.0, "slow": 6.0}},
	4: {"default": 15.0, "non_default": {"normal": 5.0, "slow": 1.5}},
	6: {"default": 25.0, "non_default": {"normal": 8.0, "slow": 3.0}}
}
SPEED_TO_ADJECTIVE = {
	1: {"25.0": "fast", "10.0": "normal", "1.5": "slow"},
	3: {"25.0": "fast", "13.0": "normal", "6.0": "slow"},
	4: {"15.0": "fast", "5.0": "normal", "1.5": "slow"},
	6: {"25.0": "fast", "8.0": "normal", "3.0": "slow"}
}
ADJECTIVE_TO_SPEED = {
	1: {v: eval(k) for k, v in SPEED_TO_ADJECTIVE[1].items()},
	3: {v: eval(k) for k, v in SPEED_TO_ADJECTIVE[3].items()},
	4: {v: eval(k) for k, v in SPEED_TO_ADJECTIVE[4].items()},
	6: {v: eval(k) for k, v in SPEED_TO_ADJECTIVE[6].items()},
}
POSSIBLE_WINDS = [
	-0.3, -0.1, 0.0
]
WIND_TO_ADJECTIVE = {
	"-0.3": "flurry",
	"-0.1": "gust",  # Chat gpt가 flurry보다 약하고 breeze보다 강한 애라고 함
	"0.0": "breeze"
}

# 0: Slow, 1: Normal, 2: Fast
IDX_TO_PARAMETERS = {
	1: {0: 1.5, 1: 10.0, 2: 25.0},
	3: {0: 6.0, 1: 13.0, 2: 25.0},
	4: {0: 1.5, 1: 5.0, 2: 15.0},
	6: {0: 3.0, 1: 8.0, 2: 25.0}
}
SCALE = 1

# text_variations: Key: main_texts // value: variations of main_texts
SEQUENTIAL_REQUIREMENTS_VARIATIONS = {
	"sequential": ["Execute these in a particular order.", "Complete these one after the other.",
				   "Do these tasks in a specific order.", "Carry out these actions sequentially.",
				   "Perform these steps in order.", "Follow these instructions in sequence.",
				   "Undertake these tasks in a particular sequence.",
				   "Accomplish these actions in a predetermined order.",
				   "Execute these procedures in the correct order.", "Work through these steps in sequence.",
				   "Perform these actions in a specific order.", "Complete these tasks in an ordered manner.",
				   "Undertake these steps sequentially.", "Carry out these instructions in order.",
				   "Follow these steps in a particular sequence.", "Do these actions in a predetermined order.",
				   "Accomplish these tasks in sequence.", "Execute these in a prescribed order.",
				   "Perform these tasks consecutively.", "Complete these tasks one by one.",
				   "Carry out these tasks in a specific order.", "Follow these procedures sequentially.",
				   "Do these in a particular order.", "Undertake these tasks in a specific order.",
				   "Work through these actions in sequence.", "Perform these tasks in a particular order.",
				   "Complete these in a specific sequence.", "Follow these instructions sequentially.",
				   "Carry out these actions one after the other.", "Do these steps in a particular order.",
				   "Undertake these procedures in sequence.", "Accomplish these tasks in an ordered manner.",
				   "Execute these in the correct order.", "Perform these actions consecutively.",
				   "Complete these steps in a specific order.", "Carry out these tasks in the correct order.",
				   "Follow these steps one by one.", "Undertake these actions in sequence.",
				   "Work through these tasks in order.", "Perform these in a particular sequence.",
				   "Complete these procedures one after the other.", "Do these in a specific order.",
				   "Carry out these steps sequentially.", "Follow these tasks in a predetermined order.",
				   "Undertake these in a specific sequence.", "Accomplish these actions consecutively.",
				   "Execute these tasks in a particular order.", "Perform these instructions in sequence.",
				   "Complete these in the correct order.", "Carry out these steps one after another."],
	"reverse": ["Do these in the opposite order.", "Carry out these in reverse sequence.",
				"Execute these in reverse order.", "Perform these in a reversed sequence.",
				"Complete these in the reverse order.", "Undertake these in the reverse order.",
				"Work through these in reverse order.", "Carry out these backwards.",
				"Execute these in the opposite sequence.", "Perform these in the inverse order.",
				"Do these in the reverse sequence.", "Complete these in reverse order.",
				"Undertake these backwards.", "Work through these in the opposite order.",
				"Carry out these in the opposite order.", "Execute these in the reverse order.",
				"Perform these backwards.", "Do these in the opposite sequence.",
				"Complete these in an inverted order.", "Undertake these in an inverse sequence.",
				"Work through these in the reverse order.", "Carry out these in a backward order.",
				"Execute these backwards.", "Perform these in the opposite order.",
				"Do these in a backward sequence.", "Complete these in the inverse order.",
				"Undertake these in the opposite order.", "Work through these backwards.",
				"Carry out these in the inverse order.", "Execute these in an inverted sequence.",
				"Perform these in the contrary order.", "Do these backwards.", "Complete these in a reverse order.",
				"Undertake these in a reversed sequence.", "Work through these in the inverted order.",
				"Carry out these in an opposite sequence.", "Execute these in a reversed order.",
				"Perform these in the contrary sequence.", "Do these in the inverted order.",
				"Complete these in a backward manner.", "Undertake these in a reverse order.",
				"Work through these in the reversed sequence.", "Carry out these in the opposite sequence.",
				"Execute these in an inverse order.", "Perform these in the backward sequence.",
				"Do these in the contrary order.", "Complete these in a reverted order.",
				"Undertake these in a backward sequence.", "Work through these in a reverse order.",
				"Carry out these in the inverted order.", "Execute these in an opposite sequence.",
				"Perform these in the opposite manner."],
	"replace 3 with 1": ["Substitute using a drawer with sliding a puck.",
						 "Exchange the drawer for a sliding puck.",
						 "Swap out the drawer for a sliding puck.",
						 "Replace the drawer with a sliding puck.",
						 "Trade the drawer for a sliding puck.",
						 "Use a sliding puck instead of a drawer.",
						 "Make the switch from a drawer to a sliding puck.",
						 "Transition from using a drawer to sliding a puck.",
						 "Choose a sliding puck over a drawer.",
						 "Opt for a sliding puck in lieu of a drawer.",
						 "Ditch the drawer and go for a sliding puck.",
						 "Convert from a drawer to a sliding puck.",
						 "Transform the drawer into a sliding puck.",
						 "Make the substitution from drawer to sliding puck.",
						 "Implement a sliding puck instead of a drawer.",
						 "Replace the use of a drawer with a sliding puck.",
						 "Utilize a sliding puck instead of a drawer.",
						 "Go for a sliding puck instead of using a drawer.",
						 "Implement a sliding puck in place of a drawer.",
						 "Select a sliding puck instead of a drawer.",
						 "Install a sliding puck in lieu of a drawer.", "Adopt a sliding puck over a drawer.",
						 "Replace the drawer's function with a sliding puck.",
						 "Use a sliding puck to take the place of a drawer.",
						 "Make the change to a sliding puck from a drawer.",
						 "Choose a sliding puck to replace a drawer.", "Pick a sliding puck instead of a drawer.",
						 "Use a sliding puck as a substitute for a drawer.",
						 "Opt to use a sliding puck instead of a drawer.",
						 "Swap the drawer for a sliding puck in function.",
						 "Incorporate a sliding puck as a replacement for a drawer.",
						 "Install a sliding puck to take over for a drawer.",
						 "Implement a sliding puck to perform the function of a drawer.",
						 "Choose to use a sliding puck in lieu of a drawer.",
						 "Adopt the use of a sliding puck instead of a drawer.",
						 "Replace the functionality of the drawer with a sliding puck.",
						 "Pick a sliding puck to take the place of a drawer.",
						 "Use a sliding puck in place of a drawer's function.",
						 "Make the transition to a sliding puck from a drawer.",
						 "Choose a sliding puck as a stand-in for a drawer.",
						 "Swap out the drawer's purpose with a sliding puck.",
						 "Install a sliding puck in place of a drawer's function.",
						 "Use a sliding puck instead of a drawer to perform the same function.",
						 "Opt to replace the drawer with a sliding puck.",
						 "Make the change to using a sliding puck instead of a drawer.",
						 "Trade the functionality of the drawer for a sliding puck.",
						 "Implement a sliding puck to replace the function of a drawer.",
						 "Choose a sliding puck to take over for a drawer's function.",
						 "Swap out the drawer for a sliding puck to perform the same task.",
						 "Pick a sliding puck over a drawer to serve the same purpose."],
	"replace 6 with 1": ["Replace opening the door with a sliding puck",
						 "Switch out the door with a sliding puck",
						 "Exchange the act of opening the door with sliding the puck",
						 "Substitute the process of opening the door with using a sliding puck",
						 "Use a sliding puck instead of opening the door",
						 "Replace the action of opening the door with sliding a puck",
						 "Opt for a sliding puck over opening the door",
						 "Make the switch from opening the door to sliding a puck",
						 "Replace the need to open the door with using a sliding puck",
						 "Choose a sliding puck instead of opening the door",
						 "Switch from opening the door to sliding a puck",
						 "Use a sliding puck as a replacement for opening the door",
						 "Replace the traditional method of opening the door with sliding a puck",
						 "Replace opening the door with sliding a puck for convenience",
						 "Substitute opening the door with sliding a puck for ease of use",
						 "Choose to slide a puck instead of opening the door",
						 "Use a sliding puck as a replacement for opening the door",
						 "Switch out the need to open the door with using a sliding puck",
						 "Replace the act of opening the door with sliding a puck for a change",
						 "Opt for a sliding puck over opening the door for simplicity",
						 "Make the switch from opening the door to sliding a puck for convenience",
						 "Use a sliding puck instead of opening the door for ease",
						 "Replace the need to open the door with sliding a puck for convenience",
						 "Choose a sliding puck instead of opening the door for simplicity",
						 "Switch from opening the door to sliding a puck for ease of use",
						 "Use a sliding puck as a replacement for opening the door for a change",
						 "Replace the traditional method of opening the door with sliding a puck for simplicity",
						 "Replace opening the door with sliding a puck for ease of access",
						 "Substitute opening the door with sliding a puck for improved accessibility",
						 "Choose to slide a puck instead of opening the door for improved accessibility",
						 "Use a sliding puck as a replacement for opening the door for accessibility",
						 "Switch out the need to open the door with using a sliding puck for improved accessibility",
						 "Replace the act of opening the door with sliding a puck for improved accessibility",
						 "Opt for a sliding puck over opening the door for improved accessibility",
						 "Make the switch from opening the door to sliding a puck for improved accessibility",
						 "Use a sliding puck instead of opening the door for improved ease of access",
						 "Replace the need to open the door with sliding a puck for ease of access",
						 "Choose a sliding puck instead of opening the door for improved ease of access",
						 "Switch from opening the door to sliding a puck for improved ease of access",
						 "Use a sliding puck as a replacement for opening the door for improved ease of access",
						 "Substitute opening the door with sliding a puck for a better user experience",
						 "Replace opening the door with sliding a puck for improved functionality",
						 "Opt for a sliding puck over opening the door for improved functionality",
						 "Make the switch from opening the door to sliding a puck for improved functionality",
						 "Use a sliding puck instead of opening the door for a better user experience",
						 "Replace the need to open the door with sliding a puck for improved functionality",
						 "Choose a sliding puck instead of opening the door for improved functionality",
						 "Switch out the need to open the door with using a sliding puck for a better user experience",
						 "Use a sliding puck as a replacement for opening the door for improved functionality",
						 "Replace the traditional method of opening the door with sliding a puck for improved functionality"],
	"replace 4 with 1": ["Swap out pressing a button with sliding a puck",
						 "Change pressing the button to sliding a puck",
						 "Substitute pressing a button with using a sliding puck",
						 "Opt for a sliding puck over pressing a button",
						 "Use a sliding puck instead of pressing a button",
						 "Replace the act of pressing a button with sliding a puck",
						 "Trade pressing a button for sliding a puck",
						 "Make the switch from pressing a button to sliding a puck",
						 "Choose a sliding puck instead of pressing a button",
						 "Switch from pressing a button to sliding a puck",
						 "Replace the need to press a button with using a sliding puck",
						 "Use a sliding puck as a replacement for pressing a button",
						 "Replace the traditional method of pressing a button with sliding a puck",
						 "Sub in sliding a puck for pressing a button",
						 "Replace pressing a button with sliding a puck for convenience",
						 "Opt for a sliding puck instead of pressing a button",
						 "Make the change from pressing a button to sliding a puck",
						 "Use a sliding puck to replace the need to press a button",
						 "Exchange pressing a button for sliding a puck",
						 "Switch out pressing a button for sliding a puck",
						 "Replace the action of pressing a button with sliding a puck",
						 "Substitute sliding a puck for pressing a button",
						 "Choose to slide a puck instead of pressing a button",
						 "Make the switch to sliding a puck instead of pressing a button",
						 "Replace pressing a button with sliding a puck for a change",
						 "Opt for a sliding puck over pressing a button for simplicity",
						 "Use a sliding puck as a replacement for pressing a button for ease",
						 "Replace the need to press a button with sliding a puck for convenience",
						 "Choose a sliding puck instead of pressing a button for simplicity",
						 "Switch from pressing a button to sliding a puck for ease of use",
						 "Use a sliding puck instead of pressing a button for a different approach",
						 "Replace the traditional method of pressing a button with sliding a puck for simplicity",
						 "Replace pressing a button with sliding a puck for improved functionality",
						 "Opt for a sliding puck over pressing a button for improved functionality",
						 "Make the switch from pressing a button to sliding a puck for improved functionality",
						 "Use a sliding puck instead of pressing a button for a better user experience",
						 "Replace the need to press a button with sliding a puck for improved functionality",
						 "Choose a sliding puck instead of pressing a button for improved functionality",
						 "Switch out pressing a button with using a sliding puck for a better user experience",
						 "Use a sliding puck as a replacement for pressing a button for improved functionality",
						 "Replace the action of pressing a button with sliding a puck for improved functionality",
						 "Substitute sliding a puck for pressing a button for improved functionality",
						 "Choose to slide a puck instead of pressing a button for improved functionality",
						 "Make the switch to sliding a puck instead of pressing a button for improved functionality",
						 "Replace pressing a button with sliding a puck for improved ease of use",
						 "Opt for a sliding puck over pressing a button for improved ease of use",
						 "Use a sliding puck as a replacement for pressing a button for improved ease of use",
						 "Replace the need to press a button with sliding a puck for improved ease of use",
						 "Choose a sliding puck instead of pressing a button for improved ease of use",
						 "Switch from pressing a button to sliding a puck for improved ease of use"],
	"replace 6 with 3": ["Replace opening the door with shutting the drawer",
						 "Swap opening the door for closing the drawer",
						 "Substitute opening the door with closing the drawer",
						 "Change opening the door to closing the drawer",
						 "Trade opening the door for closing the drawer",
						 "Opt for closing the drawer instead of opening the door",
						 "Replace the act of opening the door with closing the drawer",
						 "Make the switch from opening the door to closing the drawer",
						 "Choose closing the drawer instead of opening the door",
						 "Switch from opening the door to closing the drawer",
						 "Replace the need to open the door with closing the drawer",
						 "Use closing the drawer as a replacement for opening the door",
						 "Replace the traditional method of opening the door with closing the drawer",
						 "Sub in closing the drawer for opening the door",
						 "Replace opening the door with closing the drawer for convenience",
						 "Opt for closing the drawer over opening the door",
						 "Make the change from opening the door to closing the drawer",
						 "Use closing the drawer to replace the need to open the door",
						 "Exchange opening the door for closing the drawer",
						 "Switch out opening the door for closing the drawer",
						 "Replace the action of opening the door with closing the drawer",
						 "Substitute closing the drawer for opening the door",
						 "Choose to close the drawer instead of opening the door",
						 "Make the switch to closing the drawer instead of opening the door",
						 "Replace opening the door with closing the drawer for a change",
						 "Opt for closing the drawer instead of opening the door for simplicity",
						 "Use closing the drawer as a replacement for opening the door for ease",
						 "Replace the need to open the door with closing the drawer for convenience",
						 "Choose closing the drawer instead of opening the door for simplicity",
						 "Switch from opening the door to closing the drawer for ease of use",
						 "Use closing the drawer instead of opening the door for a different approach",
						 "Replace the traditional method of opening the door with closing the drawer for simplicity",
						 "Replace opening the door with closing the drawer for improved functionality",
						 "Opt for closing the drawer over opening the door for improved functionality",
						 "Make the switch from opening the door to closing the drawer for improved functionality",
						 "Use closing the drawer instead of opening the door for a better user experience",
						 "Replace the need to open the door with closing the drawer for improved functionality",
						 "Choose closing the drawer instead of opening the door for improved functionality",
						 "Switch out opening the door with closing the drawer for a better user experience",
						 "Use closing the drawer as a replacement for opening the door for improved functionality",
						 "Replace the action of opening the door with closing the drawer for improved functionality",
						 "Substitute closing the drawer for opening the door for improved functionality",
						 "Choose to close the drawer instead of opening the door for improved functionality",
						 "Make the switch to closing the drawer instead of opening the door for improved functionality",
						 "Replace opening the door with closing the drawer for improved ease of use",
						 "Opt for closing the drawer over opening the door for improved ease of use",
						 "Use closing the drawer as a replacement for opening the door for improved ease of use",
						 "Replace the need to open the door with closing the drawer for improved ease of use",
						 "Choose closing the drawer instead of opening the door for improved ease of use",
						 "Switch from opening the door to closing the drawer for improved ease of use"],
	"replace 4 with 3": ["Swap pressing button with closing the drawer",
						 "Trade pressing button for closing the drawer",
						 "Substitute pressing button with closing the drawer",
						 "Change pressing button to closing the drawer",
						 "Replace pressing the button with closing the drawer",
						 "Opt for closing the drawer instead of pressing button",
						 "Replace the act of pressing button with closing the drawer",
						 "Make the switch from pressing button to closing the drawer",
						 "Choose closing the drawer instead of pressing button",
						 "Switch from pressing button to closing the drawer",
						 "Replace the need to press button with closing the drawer",
						 "Use closing the drawer as a replacement for pressing button",
						 "Replace the traditional method of pressing button with closing the drawer",
						 "Sub in closing the drawer for pressing button",
						 "Replace pressing button with closing the drawer for convenience",
						 "Opt for closing the drawer over pressing button",
						 "Make the change from pressing button to closing the drawer",
						 "Use closing the drawer to replace the need to press button",
						 "Exchange pressing button for closing the drawer",
						 "Switch out pressing button for closing the drawer",
						 "Replace the action of pressing button with closing the drawer",
						 "Substitute closing the drawer for pressing button",
						 "Choose to close the drawer instead of pressing button",
						 "Make the switch to closing the drawer instead of pressing button",
						 "Replace pressing button with closing the drawer for a change",
						 "Opt for closing the drawer instead of pressing button for simplicity",
						 "Use closing the drawer as a replacement for pressing button for ease",
						 "Replace the need to press button with closing the drawer for convenience",
						 "Choose closing the drawer instead of pressing button for simplicity",
						 "Switch from pressing button to closing the drawer for ease of use",
						 "Use closing the drawer instead of pressing button for a different approach",
						 "Replace the traditional method of pressing button with closing the drawer for simplicity",
						 "Replace pressing button with closing the drawer for improved functionality",
						 "Opt for closing the drawer over pressing button for improved functionality",
						 "Make the switch from pressing button to closing the drawer for improved functionality",
						 "Use closing the drawer instead of pressing button for a better user experience",
						 "Replace the need to press button with closing the drawer for improved functionality",
						 "Choose closing the drawer instead of pressing button for improved functionality",
						 "Switch out pressing button with closing the drawer for a better user experience",
						 "Use closing the drawer as a replacement for pressing button for improved functionality",
						 "Replace the action of pressing button with closing the drawer for improved functionality",
						 "Substitute closing the drawer for pressing button for improved functionality",
						 "Choose to close the drawer instead of pressing button for improved functionality",
						 "Make the switch to closing the drawer instead of pressing button for improved functionality",
						 "Replace pressing button with closing the drawer for improved ease of use",
						 "Opt for closing the drawer over pressing button for improved ease of use",
						 "Use closing the drawer as a replacement for pressing button for improved ease of use",
						 "Replace the need to press button with closing the drawer for improved ease of use",
						 "Choose closing the drawer instead of pressing button for improved ease of use",
						 "Switch from pressing button to closing the drawer for improved ease of use"],
	"replace 1 with 6": ["Swap sliding the puck with opening the door",
						 "Trade sliding the puck for opening the door",
						 "Substitute sliding the puck with opening the door",
						 "Change sliding the puck to opening the door",
						 "Replace sliding the puck with opening the door",
						 "Opt for opening the door instead of sliding the puck",
						 "Replace the act of sliding the puck with opening the door",
						 "Make the switch from sliding the puck to opening the door",
						 "Choose opening the door instead of sliding the puck",
						 "Switch from sliding the puck to opening the door",
						 "Replace the need to slide the puck with opening the door",
						 "Use opening the door as a replacement for sliding the puck",
						 "Replace the traditional method of sliding the puck with opening the door",
						 "Sub in opening the door for sliding the puck",
						 "Replace sliding the puck with opening the door for convenience",
						 "Opt for opening the door over sliding the puck",
						 "Make the change from sliding the puck to opening the door",
						 "Use opening the door to replace the need to slide the puck",
						 "Exchange sliding the puck for opening the door",
						 "Switch out sliding the puck for opening the door",
						 "Replace the action of sliding the puck with opening the door",
						 "Substitute opening the door for sliding the puck",
						 "Choose to open the door instead of sliding the puck",
						 "Make the switch to opening the door instead of sliding the puck",
						 "Replace sliding the puck with opening the door for a change",
						 "Opt for opening the door instead of sliding the puck for simplicity",
						 "Use opening the door as a replacement for sliding the puck for ease",
						 "Replace the need to slide the puck with opening the door for convenience",
						 "Choose opening the door instead of sliding the puck for simplicity",
						 "Switch from sliding the puck to opening the door for ease of use",
						 "Use opening the door instead of sliding the puck for a different approach",
						 "Replace the traditional method of sliding the puck with opening the door for simplicity",
						 "Replace sliding the puck with opening the door for improved functionality",
						 "Opt for opening the door over sliding the puck for improved functionality",
						 "Make the switch from sliding the puck to opening the door for improved functionality",
						 "Use opening the door instead of sliding the puck for a better user experience",
						 "Replace the need to slide the puck with opening the door for improved functionality",
						 "Choose opening the door instead of sliding the puck for improved functionality",
						 "Switch out sliding the puck with opening the door for a better user experience",
						 "Use opening the door as a replacement for sliding the puck for improved functionality",
						 "Replace the action of sliding the puck with opening the door for improved functionality",
						 "Substitute opening the door for sliding the puck for improved functionality",
						 "Choose to open the door instead of sliding the puck for improved functionality",
						 "Make the switch to opening the door instead of sliding the puck for improved functionality",
						 "Replace sliding the puck with opening the door for improved ease of use",
						 "Opt for opening the door over sliding the puck for improved ease of use",
						 "Use opening the door as a replacement for sliding the puck for improved ease of use",
						 "Replace the need to slide the puck with opening the door for improved ease of use",
						 "Choose opening the door instead of sliding the puck for improved ease of use",
						 "Switch from sliding the puck to opening the door for improved ease of use"],
	"replace 1 with 3": ["Substitute pulling the lever for sliding the puck.",
						 "Exchange operating the handle for sliding the puck.",
						 "Swap turning the knob for sliding the puck.",
						 "Replace pushing the slider with closing the drawer.",
						 "Replace gliding the panel with shutting the drawer.",
						 "Substitute pulling the slide with closing the drawer.",
						 "Exchange manipulating the lever for sliding the puck.",
						 "Swap closing the flap with shutting the drawer.",
						 "Replace closing the hatch with closing the drawer.",
						 "Replace shifting the gate with closing the drawer.",
						 "Substitute drawing the latch for sliding the puck.",
						 "Exchange engaging the lock for sliding the puck.",
						 "Swap securing the catch for closing the drawer.",
						 "Replace clasping the fastener with closing the drawer.",
						 "Replace snapping the lock with closing the drawer.",
						 "Substitute locking the clasp for sliding the puck.",
						 "Exchange shutting the seal for sliding the puck.",
						 "Swap covering the lid with closing the drawer.",
						 "Replace sealing the container with shutting the drawer.",
						 "Replace lowering the shield with closing the drawer.",
						 "Substitute tucking in the panel for sliding the puck.",
						 "Exchange folding down the cover for sliding the puck.",
						 "Swap pushing the door in for closing the drawer.",
						 "Replace flipping the flap down with shutting the drawer.",
						 "Replace rotating the panel down with closing the drawer.",
						 "Substitute dropping the gate with sliding the puck.",
						 "Exchange lowering the sash for sliding the puck.",
						 "Swap rolling down the shutter for closing the drawer.",
						 "Replace dropping the curtain with shutting the drawer.",
						 "Replace lowering the shade with closing the drawer.",
						 "Substitute closing the blind for sliding the puck.",
						 "Exchange drawing the screen for sliding the puck.",
						 "Swap bringing the partition together for closing the drawer.",
						 "Replace pushing the barrier closed with shutting the drawer.",
						 "Replace tucking in the sheet with closing the drawer.",
						 "Substitute pulling the cover over for sliding the puck.",
						 "Exchange sliding the shield in for sliding the puck.",
						 "Swap folding the panel in for closing the drawer.",
						 "Replace pushing the panel down for shutting the drawer.",
						 "Replace rotating the shield for closing the drawer.",
						 "Substitute sliding the screen closed for sliding the puck.",
						 "Exchange lowering the shutter for sliding the puck.",
						 "Swap bringing the door together for closing the drawer.",
						 "Replace drawing the partition closed with shutting the drawer.",
						 "Replace folding the panel over for closing the drawer.",
						 "Substitute rolling the shutter down for sliding the puck.",
						 "Exchange closing the blind for sliding the puck.",
						 "Swap drawing the screen closed for closing the drawer.",
						 "Replace sliding the panel closed for shutting the drawer.",
						 "Replace bringing the partition closed for closing the drawer."],
	"replace 3 with 4": ['Swap the drawer for the button',
						 'Exchange the drawer for the button',
						 'Replace the drawer with a button press',
						 'Substitute closing the drawer for pressing the button',
						 'Trade in closing the drawer for pressing the button',
						 'Replace the act of closing the drawer with pressing the button',
						 'Switch closing the drawer with pressing the button',
						 'Replace the drawer closing with button pressing',
						 'Replace the act of shutting the drawer with pressing the button',
						 'Replace the action of closing the drawer with pressing the button',
						 'Trade the drawer for the button',
						 'Replace closing the drawer with pushing the button',
						 'Replace closing the drawer with a button push',
						 'Substitute pressing the button for closing the drawer',
						 'Switch the drawer for the button',
						 'Replace the act of shutting the drawer with the press of a button',
						 'Exchange closing the drawer for pressing the button',
						 'Replace shutting the drawer with pushing the button',
						 'Replace drawer closure with button press',
						 'Trade the drawer for a button press',
						 'Swap out closing the drawer for pressing the button',
						 'Replace the closing of the drawer with pressing the button',
						 'Trade closing the drawer for pushing the button',
						 'Replace the drawer close with a button press',
						 'Replace the action of shutting the drawer with pushing the button',
						 'Trade in closing the drawer for pushing the button',
						 'Replace the act of closing the drawer with a button press',
						 'Replace the act of shutting the drawer with a button push',
						 'Replace drawer closure with a button press',
						 'Switch the closing of the drawer with pressing the button',
						 'Replace the action of closing the drawer with the push of a button',
						 'Substitute shutting the drawer with pressing the button',
						 'Replace shutting the drawer with a button push',
						 'Replace drawer closure with button push',
						 'Exchange shutting the drawer for pressing the button',
						 'Trade closing the drawer for a button press',
						 'Replace the act of shutting the drawer with a button press',
						 'Replace the action of closing the drawer with a button press',
						 'Replace the closing of the drawer with pushing the button',
						 'Trade the drawer for a button push',
						 'Replace the act of shutting the drawer with button pressing',
						 'Replace the action of closing the drawer with button pressing',
						 'Swap closing the drawer for pushing the button',
						 'Exchange shutting the drawer for a button press',
						 'Replace the closing of the drawer with a button push',
						 'Trade in closing the drawer for a button press',
						 'Replace drawer closure with a button push',
						 'Replace shutting the drawer with button pressing',
						 'Substitute the button press for closing the drawer'],
	"replace 3 with 6": ["Swap closing the drawer with opening the door",
						 "Trade closing the drawer for opening the door",
						 "Substitute closing the drawer with opening the door",
						 "Change closing the drawer to opening the door",
						 "Replace closing the drawer with opening the door",
						 "Opt for opening the door instead of closing the drawer",
						 "Replace the act of closing the drawer with opening the door",
						 "Make the switch from closing the drawer to opening the door",
						 "Choose opening the door instead of closing the drawer",
						 "Switch from closing the drawer to opening the door",
						 "Replace the need to close the drawer with opening the door",
						 "Use opening the door as a replacement for closing the drawer",
						 "Replace the traditional method of closing the drawer with opening the door",
						 "Sub in opening the door for closing the drawer",
						 "Replace closing the drawer with opening the door for convenience",
						 "Opt for opening the door over closing the drawer",
						 "Make the change from closing the drawer to opening the door",
						 "Use opening the door to replace the need to close the drawer",
						 "Exchange closing the drawer for opening the door",
						 "Switch out closing the drawer for opening the door",
						 "Replace the action of closing the drawer with opening the door",
						 "Substitute opening the door for closing the drawer",
						 "Choose to open the door instead of closing the drawer",
						 "Make the switch to opening the door instead of closing the drawer",
						 "Replace closing the drawer with opening the door for a change",
						 "Opt for opening the door instead of closing the drawer for simplicity",
						 "Use opening the door as a replacement for closing the drawer for ease",
						 "Replace the need to close the drawer with opening the door for convenience",
						 "Choose opening the door instead of closing the drawer for simplicity",
						 "Switch from closing the drawer to opening the door for ease of use",
						 "Use opening the door instead of closing the drawer for a different approach",
						 "Replace the traditional method of closing the drawer with opening the door for simplicity",
						 "Replace closing the drawer with opening the door for improved functionality",
						 "Opt for opening the door over closing the drawer for improved functionality",
						 "Make the switch from closing the drawer to opening the door for improved functionality",
						 "Use opening the door instead of closing the drawer for a better user experience",
						 "Replace the need to close the drawer with opening the door for improved functionality",
						 "Choose opening the door instead of closing the drawer for improved functionality",
						 "Switch out closing the drawer with opening the door for a better user experience",
						 "Use opening the door as a replacement for closing the drawer for improved functionality",
						 "Replace the action of closing the drawer with opening the door for improved functionality",
						 "Substitute opening the door for closing the drawer for improved functionality",
						 "Choose to open the door instead of closing the drawer for improved functionality",
						 "Make the switch to opening the door instead of closing the drawer for improved functionality",
						 "Replace closing the drawer with opening the door for improved ease of use",
						 "Opt for opening the door over closing the drawer for improved ease of use",
						 "Use opening the door as a replacement for closing the drawer for improved ease of use",
						 "Replace the need to close the drawer with opening the door for improved ease of use",
						 "Choose opening the door instead of closing the drawer for improved ease of use",
						 "Switch from closing the drawer to opening the door for improved ease of use"],
	"replace 6 with 4": ["Swap opening the door with pressing the button",
						 "Trade opening the door for pressing the button",
						 "Substitute opening the door with pressing the button",
						 "Change opening the door to pressing the button",
						 "Replace opening the door with pressing the button",
						 "Opt for pressing the button instead of opening the door",
						 "Replace the act of opening the door with pressing the button",
						 "Make the switch from opening the door to pressing the button",
						 "Choose pressing the button instead of opening the door",
						 "Switch from opening the door to pressing the button",
						 "Replace the need to open the door with pressing the button",
						 "Use pressing the button as a replacement for opening the door",
						 "Replace the traditional method of opening the door with pressing the button",
						 "Sub in pressing the button for opening the door",
						 "Replace opening the door with pressing the button for convenience",
						 "Opt for pressing the button over opening the door",
						 "Make the change from opening the door to pressing the button",
						 "Use pressing the button to replace the need to open the door",
						 "Exchange opening the door for pressing the button",
						 "Switch out opening the door for pressing the button",
						 "Replace the action of opening the door with pressing the button",
						 "Substitute pressing the button for opening the door",
						 "Choose to press the button instead of opening the door",
						 "Make the switch to pressing the button instead of opening the door",
						 "Replace opening the door with pressing the button for a change",
						 "Opt for pressing the button instead of opening the door for simplicity",
						 "Use pressing the button as a replacement for opening the door for ease",
						 "Replace the need to open the door with pressing the button for convenience",
						 "Choose pressing the button instead of opening the door for simplicity",
						 "Switch from opening the door to pressing the button for ease of use",
						 "Use pressing the button instead of opening the door for a different approach",
						 "Replace the traditional method of opening the door with pressing the button for simplicity",
						 "Replace opening the door with pressing the button for improved functionality",
						 "Opt for pressing the button over opening the door for improved functionality",
						 "Make the switch from opening the door to pressing the button for improved functionality",
						 "Use pressing the button instead of opening the door for a better user experience",
						 "Replace the need to open the door with pressing the button for improved functionality",
						 "Choose pressing the button instead of opening the door for improved functionality",
						 "Switch out opening the door for pressing the button for a better user experience",
						 "Use pressing the button as a replacement for opening the door for improved functionality",
						 "Replace the action of opening the door with pressing the button for improved functionality",
						 "Substitute pressing the button for opening the door for improved functionality",
						 "Choose to press the button instead of opening the door for improved functionality",
						 "Make the switch to pressing the button instead of opening the door for improved functionality",
						 "Replace opening the door with pressing the button for improved ease of use",
						 "Opt for pressing the button over opening the door for improved ease of use",
						 "Use pressing the button as a replacement for opening the door for improved ease of use",
						 "Replace the need to open the door with pressing the button for improved ease of use",
						 "Choose pressing the button instead of opening the door for improved ease of use",
						 "Switch from opening the door to pressing the button for improved ease of use"],
	"replace 1 with 4": ["Make the change from sliding the puck to pushing the button",
						 "Opt for pushing the button instead of sliding the puck",
						 "Switch to pushing the button instead of sliding the puck",
						 "Replace the act of sliding the puck with pushing the button",
						 "Choose pushing the button over sliding the puck",
						 "Exchange sliding the puck for pushing the button",
						 "Trade sliding the puck for pushing the button",
						 "Sub in pushing the button for sliding the puck",
						 "Make the switch from sliding the puck to pressing a button",
						 "Use a button press to replace the need to slide the puck",
						 "Replace sliding the puck with the action of pressing a button",
						 "Swap sliding the puck with pushing a button",
						 "Substitute pushing a button for sliding the puck",
						 "Change sliding the puck to pushing a button",
						 "Replace sliding the puck with a button press",
						 "Opt for a button press over sliding the puck",
						 "Switch from sliding the puck to pressing a button",
						 "Use a button press to replace sliding the puck",
						 "Exchange sliding the puck for a button press",
						 "Trade sliding the puck for a button press",
						 "Substitute a button press for sliding the puck",
						 "Choose to push a button instead of sliding the puck",
						 "Make the switch to pushing a button instead of sliding the puck",
						 "Replace sliding the puck with a button press for a change",
						 "Opt for a button press instead of sliding the puck for simplicity",
						 "Use a button press as a replacement for sliding the puck for ease",
						 "Replace the need to slide the puck with a button press for convenience",
						 "Choose a button press instead of sliding the puck for simplicity",
						 "Switch from sliding the puck to pushing a button for ease of use",
						 "Use a button press instead of sliding the puck for a different approach",
						 "Replace the traditional method of sliding the puck with a button press for simplicity",
						 "Replace sliding the puck with pushing a button for improved functionality",
						 "Opt for a button press over sliding the puck for improved functionality",
						 "Make the switch from sliding the puck to pushing a button for improved functionality",
						 "Use a button press instead of sliding the puck for a better user experience",
						 "Replace the need to slide the puck with pushing a button for convenience",
						 "Choose pushing a button instead of sliding the puck for efficiency",
						 "Trade sliding the puck for a quick button press",
						 "Substitute a quick button press for sliding the puck",
						 "Switch to a quick button press instead of sliding the puck",
						 "Make the change from sliding the puck to a quick button press",
						 "Replace the act of sliding the puck with a quick button press",
						 "Opt for a quick button press over sliding the puck",
						 "Use a quick button press to replace the need to slide the puck",
						 "Exchange sliding the puck for a quick button press",
						 "Trade sliding the puck for a fast button press",
						 "Substitute a fast button press for sliding the puck",
						 "Switch to a fast button press instead of sliding the puck",
						 "Make the change from sliding the puck to a fast button press"],
	"replace 4 with 6": [
		"Swap out button-pressing for door-opening",
		"Substitute button-pressing with door-opening",
		"Exchange button-pressing for door-opening",
		"Replace the act of pressing the button with opening the door",
		"Switch out pressing the button with opening the door",
		"Use opening the door instead of pressing the button",
		"Prefer opening the door over pressing the button",
		"Choose opening the door in place of pressing the button",
		"Opt for opening the door instead of pressing the button",
		"Trade in pressing the button for opening the door",
		"Replace the button press with door opening",
		"Use door opening instead of button pressing",
		"Substitute door opening for button pressing",
		"Prefer door opening over button pressing",
		"Exchange button pressing for door opening",
		"Make the switch from button pressing to door opening",
		"Choose door opening instead of button pressing",
		"Opt for door opening in place of button pressing",
		"Trade in button pressing for door opening",
		"Replace button pressing with door opening",
		"Switch from pressing the button to opening the door",
		"Use opening the door as an alternative to pressing the button",
		"Prefer opening the door as a replacement for pressing the button",
		"Choose opening the door as a substitute for pressing the button",
		"Opt for opening the door over pressing the button",
		"Trade pressing the button for opening the door",
		"Replace the act of pressing the button with the act of opening the door",
		"Exchange the act of pressing the button with the act of opening the door",
		"Substitute the act of opening the door for the act of pressing the button",
		"Choose to open the door rather than press the button",
		"Select opening the door over pressing the button",
		"Prefer opening the door to pressing the button",
		"Opt for opening the door instead of pressing the button",
		"Make the switch to opening the door from pressing the button",
		"Trade out button pressing for door opening",
		"Replace button pressing with the action of opening the door",
		"Swap button pressing for door opening",
		"Substitute opening the door for pressing the button",
		"Exchange opening the door for pressing the button",
		"Choose to open the door instead of press the button",
		"Prefer to open the door instead of press the button",
		"Opt to open the door instead of press the button",
		"Trade pressing the button for opening the door",
		"Replace button pressing with the act of opening the door",
		"Switch to opening the door instead of pressing the button",
		"Use opening the door rather than pressing the button",
		"Prefer opening the door over pressing the button",
		"Choose opening the door in lieu of pressing the button",
		"Opt for opening the door as a substitute for pressing the button",
		"Trade in button pressing for opening the door",
		"Replace pressing the button with opening the door",
		"Swap pressing the button for opening the door",
		"Substitute opening the door for the button press",
		"Exchange opening the door for the button press",
		"Choose to open the door rather than press the button",
		"Prefer opening the door to pressing the button",
		"Opt for opening the door over pressing the button",
		"Trade pressing the button for opening the door"
	]
}

# for k, v in SEQUENTIAL_REQUIREMENTS_VARIATIONS.items():
# 	SEQUENTIAL_REQUIREMENTS_VARIATIONS[k] = v[:2]

NON_FUNCTIONALITIES_VARIATIONS = {
	"wind": ["wind blowing"],
	"speed": ["robot arm's speed"]
}