from collections import defaultdict
from itertools import permutations
from itertools import product
from typing import List

from comde.utils.common.natural_languages.lang_representation import SkillRepresentation
from comde_rlbench.RLBench.rlbench.comde_const import COMDE_SKILLS_TO_IDX
from comde_rlbench.RLBench.rlbench.comde_const import COMDE_WEIGHTS

OBS_DIM = 387
ACT_DIM = 11

COMDE_IDX_TO_SKILLS = {v: k for k, v in COMDE_SKILLS_TO_IDX.items()}
COMDE_SKILLS_POSITIONS = {
	"leftmost": [0, 1, 2],
	"left": [3, 4, 5],
	"right": [6, 7, 8],
	"rightmost": [9, 10, 11]
}


def tasks_to_idxs(tasks: List) -> List[int]:
	return [COMDE_SKILLS_TO_IDX[task] for task in tasks]  # [1, 3, 7, 9]


RLBENCH_ALL_TASKS = list(product(*list(COMDE_SKILLS_POSITIONS.values())))

SEQUENTIAL_REQUIREMENT = ["sequential", "reverse"]
for (a, b) in list(permutations(COMDE_WEIGHTS.keys(), 2)):
	SEQUENTIAL_REQUIREMENT.append(f"replace {a} with {b}")

WEIGHT_TO_ADJECTIVE = {}
for skill, weights in COMDE_WEIGHTS.items():
	WEIGHT_TO_ADJECTIVE[skill] = {weight: adj for weight, adj in zip(weights, ["normal", "heavy", "light"])}


def get_weight(skill_idx: int, adj: str):
	"""
		adj: default, heavy, light
	"""
	obj_weights = COMDE_WEIGHTS[skill_idx]
	if adj == "default":
		return obj_weights[0]
	elif adj == "heavy":
		return obj_weights[1]
	elif adj == "light":
		return obj_weights[2]
	else:
		raise NotImplementedError(f"Undefined weight adjective: {adj}")


def object_in_task(task: str):
	if "door" in task:
		return "door"
	elif "fridge" in task:
		return "fridge"
	elif "drawer" in task:
		return "drawer"
	elif "lamp" in task:
		return "lamp"
	elif "button" in task:
		return "button"
	elif "switch" in task:
		return "switch"
	elif "microwave" in task:
		return "microwave"
	elif "box" in task:
		return "box"
	elif "block" in task:
		return "block"
	else:
		raise NotImplementedError(f"{task} has no object identifier")


# NOTE: """order matters""". it mapped to one-hot representation.
main_texts = [
	"open door",
	"close door",
	"close fridge",
	"open drawer",
	"close drawer",
	"lamp off",
	"push button",
	"lamp on",
	"press switch",
	"close microwave",
	"open box",
	"slide block to target",
]
texts_variations = {
	mt: [mt] for mt in main_texts
}

skill_infos = defaultdict(list)
for idx, (key, variations) in enumerate(texts_variations.items()):
	for text in variations:
		skill_rep = SkillRepresentation(
			title=key,
			variation=text,
			vec="override this using language model",
			index=idx
		)
		skill_infos[key].append(skill_rep)

SEQUENTIAL_REQUIREMENTS_VARIATIONS = {
	"sequential": ["Execute these in a particular order.", "Complete these one after the other.",
				   "Do these tasks in a specific order.", "Carry out these actions sequentially.",
				   "Perform these steps in order.", "Follow these instructions in sequence.",
				   "Undertake these tasks in a particular sequence.",
				   "Accomplish these actions in a predetermined order.",
				   "Execute these procedures in the correct order.", "Work through these steps in sequence.",
				   "Perform these actions in a specific order.", "Complete these tasks in an ordered manner.",
				   "Undertake these steps sequentially.", "Carry out these instructions in order.",
				   "Follow these steps in a particular sequence.", "Do these actions in a predetermined order.",
				   "Accomplish these tasks in sequence.", "Execute these in a prescribed order.",
				   "Perform these tasks consecutively.", "Complete these tasks one by one.",
				   "Carry out these tasks in a specific order.", "Follow these procedures sequentially.",
				   "Do these in a particular order.", "Undertake these tasks in a specific order.",
				   "Work through these actions in sequence.", "Perform these tasks in a particular order.",
				   "Complete these in a specific sequence.", "Follow these instructions sequentially.",
				   "Carry out these actions one after the other.", "Do these steps in a particular order.",
				   "Undertake these procedures in sequence.", "Accomplish these tasks in an ordered manner.",
				   "Execute these in the correct order.", "Perform these actions consecutively.",
				   "Complete these steps in a specific order.", "Carry out these tasks in the correct order.",
				   "Follow these steps one by one.", "Undertake these actions in sequence.",
				   "Work through these tasks in order.", "Perform these in a particular sequence.",
				   "Complete these procedures one after the other.", "Do these in a specific order.",
				   "Carry out these steps sequentially.", "Follow these tasks in a predetermined order.",
				   "Undertake these in a specific sequence.", "Accomplish these actions consecutively.",
				   "Execute these tasks in a particular order.", "Perform these instructions in sequence.",
				   "Complete these in the correct order.", "Carry out these steps one after another."],
	"reverse": ["Do these in the opposite order.", "Carry out these in reverse sequence.",
				"Execute these in reverse order.", "Perform these in a reversed sequence.",
				"Complete these in the reverse order.", "Undertake these in the reverse order.",
				"Work through these in reverse order.", "Carry out these backwards.",
				"Execute these in the opposite sequence.", "Perform these in the inverse order.",
				"Do these in the reverse sequence.", "Complete these in reverse order.",
				"Undertake these backwards.", "Work through these in the opposite order.",
				"Carry out these in the opposite order.", "Execute these in the reverse order.",
				"Perform these backwards.", "Do these in the opposite sequence.",
				"Complete these in an inverted order.", "Undertake these in an inverse sequence.",
				"Work through these in the reverse order.", "Carry out these in a backward order.",
				"Execute these backwards.", "Perform these in the opposite order.",
				"Do these in a backward sequence.", "Complete these in the inverse order.",
				"Undertake these in the opposite order.", "Work through these backwards.",
				"Carry out these in the inverse order.", "Execute these in an inverted sequence.",
				"Perform these in the contrary order.", "Do these backwards.", "Complete these in a reverse order.",
				"Undertake these in a reversed sequence.", "Work through these in the inverted order.",
				"Carry out these in an opposite sequence.", "Execute these in a reversed order.",
				"Perform these in the contrary sequence.", "Do these in the inverted order.",
				"Complete these in a backward manner.", "Undertake these in a reverse order.",
				"Work through these in the reversed sequence.", "Carry out these in the opposite sequence.",
				"Execute these in an inverse order.", "Perform these in the backward sequence.",
				"Do these in the contrary order.", "Complete these in a reverted order.",
				"Undertake these in a backward sequence.", "Work through these in a reverse order.",
				"Carry out these in the inverted order.", "Execute these in an opposite sequence.",
				"Perform these in the opposite manner."],
	"replace 0 with 1": ["Close the door instead of leaving it open.",
						 "Shut the door rather than leaving it open.",
						 "Don't leave the door open. Close it.",
						 "Ensure that the door is not left open by closing it.",
						 "Close the door instead of leaving it unclosed."],
	"replace 0 with 2": ["Replace 'open door' with 'close fridge'",
						 "'open door' should be replaced with 'close fridge'",
						 "The action 'open door' must be changed to 'close fridge'",
						 "Substitute 'open door' for 'close fridge'",
						 "Transform 'open door' into 'close fridge'"],
	"replace 0 with 3": ["Replace 'open door' with 'open drawer'.",
						 "Substitute 'open door' with 'open drawer'.",
						 "Exchange 'open door' with 'open drawer'.",
						 "'Open drawer' should be used instead of 'open door'.",
						 "Use 'open drawer' instead of 'open door'."],
	"replace 0 with 4": ["Substitute 'open door' with 'close drawer'.",
						 "Replace 'open door' with 'close drawer'.",
						 "Exchange 'open door' for 'close drawer'.",
						 "Use 'close drawer' instead of 'open door'.",
						 "Swap 'open door' with 'close drawer'."],
	"replace 0 with 5": ["Substitute 'open door' with 'lamp off'.",
						 "Swap 'open door' for 'lamp off'.",
						 "Replace 'open door' with 'lamp off'.",
						 "Exchange 'open door' with 'lamp off'.",
						 "Change 'open door' to 'lamp off'."],
	"replace 0 with 6": ['Substitute \'open door\' with \'push button\'.',
						 'Exchange the phrase \'open door\' for \'push button\'.',
						 'Replace the words \'open door\' with \'push button\'.',
						 'Use \'push button\' instead of \'open door\'.',
						 'Transform \'open door\' to \'push button\'.'],
	"replace 0 with 7": ["Substitute 'open door' with 'lamp on'.",
						 "'Lamp on' can be used instead of 'open door'.",
						 "'Open door' should be replaced by 'lamp on'.",
						 "Use 'lamp on' instead of 'open door'.",
						 "'Lamp on' is the replacement for 'open door'."],
	"replace 0 with 8": ['Substitute the phrase "open door" with "press switch".',
						 'Switch the wording from "open door" to "press switch".',
						 'Exchange "open door" for "press switch".',
						 'Replace the term "open door" with "press switch".',
						 'Use "press switch" instead of "open door" in your language.'],
	"replace 0 with 9": ["Substitute 'open door' with 'close microwave'.",
						 "Replace 'open door' with 'close microwave'.",
						 "Exchange 'open door' for 'close microwave'.",
						 "'open door' needs to be changed to 'close microwave'.",
						 "Use 'close microwave' instead of 'open door'."],
	"replace 0 with 10": ["Replace 'open door' with 'open box'.",
						  "'Open door' should be replaced with 'open box'.",
						  "Substitute 'open door' with 'open box'.",
						  "Change 'open door' to 'open box'.",
						  "Swap 'open door' for 'open box'."],
	"replace 0 with 11": ['Substitute the phrase "open door" with "slide block to target".',
						  'In place of "open door", use "slide block to target".',
						  'Exchange "open door" with "slide block to target".',
						  'Replace "open door" with "slide block to target".',
						  'Swap out "open door" for "slide block to target".'],
	"replace 1 with 0": ['Substitute "close door" with "open door".',
						 'Change "close door" to "open door".',
						 'Replace the phrase "close door" with "open door".',
						 'Exchange "close door" with "open door".',
						 'Switch "close door" to "open door".'],
	"replace 1 with 2": ["Substitute 'close door' with 'close fridge'.",
						 "Replace 'close door' with 'close fridge'.",
						 "Exchange 'close door' for 'close fridge'.",
						 "Switch 'close door' with 'close fridge'.",
						 "Replace the phrase 'close door' with 'close fridge'."],
	"replace 1 with 3": ["Substitute 'close door' for 'open drawer'.",
						 "Exchange 'close door' with 'open drawer'.",
						 "'Close door' should be replaced with 'open drawer'.",
						 "'Open drawer' is the new 'close door'.",
						 "Change 'close door' to 'open drawer'."]
	,
	"replace 1 with 4": ['Substitute "close door" with "close drawer".',
						 'Change "close door" to "close drawer".',
						 'Replace the phrase "close door" with "close drawer".',
						 'Switch "close door" to "close drawer".',
						 'Exchange "close door" for "close drawer".'],
	"replace 1 with 5": ['Turn off the lamp instead of closing the door.',
						 'Exchange "close door" with "turn off lamp".',
						 'Replace "close door" with the phrase "turn off lamp".',
						 'Substitute "close door" for "turn off lamp".',
						 'Change "close door" to "turn off lamp".'],
	"replace 1 with 6": ['Substitute \'close door\' with \'push button\'.',
						 'Replace the phrase \'close door\' with \'push button\'.',
						 'Swap out \'close door\' and put in \'push button\'.',
						 'Change the wording from \'close door\' to \'push button\'.',
						 'Substitute the expression \'close door\' for \'push button\'.'],
	"replace 1 with 7": ["Change 'close door' to 'turn on lamp'",
						 "Substitute 'close door' with 'turn on lamp'",
						 "Replace 'close door' with 'switch on lamp'",
						 "Exchange 'close door' for 'light up lamp'",
						 "Switch 'close door' with 'turn on lamp'"],
	"replace 1 with 8": ["Swap out 'close door' and insert 'press switch'.",
						 "Substitute 'close door' with 'press switch'.",
						 "Replace the phrase 'close door' with 'press switch'.",
						 "Exchange 'close door' for 'press switch'.",
						 "Use 'press switch' instead of 'close door'."],
	"replace 1 with 9": ['Substitute "close door" with "close microwave".',
						 'Replace the phrase "close door" with "close microwave".',
						 'Exchange "close door" with "close microwave".',
						 'Switch out "close door" with "close microwave".',
						 'Swap "close door" for "close microwave".'],
	"replace 1 with 10": ["Substitute 'close door' with 'open box'",
						  "Replace 'close door' with 'open box'",
						  "'Open box' is the new wording for 'close door'",
						  "Exchange 'close door' for 'open box'",
						  "Use 'open box' instead of 'close door'"],
	"replace 1 with 11": ['Replace the phrase "close door" with "slide block to target".',
						  'Substitute "close door" with "slide block to target".',
						  'Use "slide block to target" instead of "close door".',
						  'Exchange "close door" for "slide block to target".',
						  'Swap out "close door" for "slide block to target".'],
	"replace 2 with 0": ['Substitute the phrase "close fridge" with "open door".',
						 'Change "close fridge" to "open door".',
						 'Replace the instruction "close the fridge" with "open the door".',
						 'Switch out "close the fridge" for "open the door".',
						 'Exchange the phrase "close fridge" for "open door".'],
	"replace 2 with 1": ['Substitute "close fridge" with "close door".',
						 'Replace "close fridge" with "close door".',
						 'Exchange "close fridge" with "close door".',
						 'Swap "close fridge" with "close door".',
						 'Substitute the phrase "close fridge" with "close door".'],
	"replace 2 with 3": ['Change the phrase "close fridge" to "open drawer"',
						 'Exchange the words "close fridge" for "open drawer"',
						 'Substitute "close fridge" with "open drawer"',
						 'Replace "close fridge" with "open drawer"', 'Convert "close fridge" to "open drawer"']
	,
	"replace 2 with 4": ['Change "close fridge" to "close drawer"',
						 'Replace "close fridge" with "close drawer"',
						 "Substitute 'close fridge' with 'close drawer'",
						 "Exchange 'close fridge' with 'close drawer'",
						 "Convert 'close fridge' to 'close drawer'"],
	"replace 2 with 5": ['Turn off the light instead of closing the fridge.',
						 'When you finish taking food from the fridge, turn off the light instead of closing the door.',
						 'Instead of closing the fridge, make sure to turn off the light.',
						 'Replace "close fridge" with "turn off lamp".',
						 'Don’t say "close fridge", say "turn off the lamp".'],
	"replace 2 with 6": ['Change "close fridge" to "push button".', 'Substitute "close fridge" with "push button".',
						 'Transform "close fridge" into "push button".', 'Convert "close fridge" to "push button".',
						 'Exchange "close fridge" for "push button".'],
	"replace 2 with 7": ["Switch on the lamp instead of closing the fridge.",
						 "Instead of shutting the refrigerator, turn on the lamp.",
						 "Swap 'close fridge' with 'lamp on'.",
						 "Replace 'close fridge' with 'turn on lamp'.",
						 "Exchange 'close the fridge' with 'switch on the lamp'."],
	"replace 2 with 8": ["Substitute 'close fridge' with 'press switch'",
						 "Replace 'close fridge' with 'press switch'",
						 "Switch 'close fridge' with 'press switch'",
						 "Exchange 'close fridge' with 'press switch'",
						 "Replace the phrase 'close fridge' with 'press switch'"],
	"replace 2 with 9": ['Substitute "close fridge" with "close microwave".',
						 'Replace the phrase "close fridge" with "close microwave".',
						 'Exchange "close fridge" with "close microwave".',
						 'Swap out "close fridge" with "close microwave".',
						 'Substitute the words "close fridge" with "close microwave".'],
	"replace 2 with 10": ['Substitute the phrase "close fridge" with "open box".',
						  'Replace the words "close fridge" for "open box".',
						  'Exchange "close fridge" with "open box".',
						  'Switch "close fridge" to "open box".',
						  'The instruction is to change "close fridge" to "open box".'
						  ],
	"replace 2 with 11": [
		"Change the instruction 'close the fridge' to 'move the barrier towards the desired location.' ",
		"'Slide the block to the destination' instead of 'Close the fridge'.",
		"Switch 'Close the fridge' to 'Move the block as per the target'.",
		"Exchange 'Close fridge' with 'Push the block towards the goal'.",
		"Substitute 'Close fridge' with 'Slide block towards the desired location'."],
	"replace 3 with 0": ['Substitute "open drawer" with "open door"',
						 'Replace the phrase "open drawer" with "open door"',
						 "Change 'open drawer' to 'open door'",
						 "Transform 'open drawer' into 'open door'",
						 "Swap 'open drawer' with 'open door'"],
	"replace 3 with 1": ['Replace the command of opening the drawer with closing the door.',
						 'Replace the instruction to open the drawer with shutting the door.',
						 'Substitute "open drawer" with "close door".',
						 "The action of opening the drawer should be replaced with closing the door.",
						 "Change the direction to 'close the door' instead of 'open drawer'."],
	"replace 3 with 2": ["Substitute 'open drawer' with 'close fridge'",
						 "Use 'close fridge' instead of 'open drawer'",
						 "'Close fridge' should be used in place of 'open drawer'",
						 "Replace 'open drawer' with 'close fridge'",
						 "Exchange 'open drawer' with 'close fridge'"],
	"replace 3 with 4": ["Replace the phrase 'open drawer' with 'close drawer'.",
						 "Switch 'open drawer' with 'close drawer'.",
						 "Substitute 'open drawer' with 'close drawer'.",
						 "Exchange 'open drawer' with 'close drawer'.",
						 "Change the command from 'open drawer' to 'close drawer'."],
	"replace 3 with 5": ['Turn off the lamp.', 'Switch off the lamp.', 'Power down the lamp.', 'Put out the light.',
						 'Deactivate the lamp.'],
	"replace 3 with 6": ["Substitute 'push button' for 'open drawer'.",
						 "Replace the phrase 'open drawer' with 'push button'.",
						 "'Push button' should be used instead of 'open drawer'.",
						 "Swap 'open drawer' with 'push button'.",
						 "Change 'open drawer' to 'push button'."],
	"replace 3 with 7":
		["Substitute 'open drawer' with 'lamp on'",
		 "Replace 'open drawer' with 'lamp on'",
		 "Exchange 'open drawer' with 'lamp on'",
		 "Switch 'open drawer' to 'lamp on'",
		 "Convert 'open drawer' to 'lamp on'"],
	"replace 3 with 8": ['Use the switch instead of opening the drawer.',
						 'Replace "open drawer" with "press switch".',
						 'Substitute opening the drawer with pressing the switch.',
						 'Instead of opening the drawer, use the switch.',
						 'Exchange the action of opening the drawer with that of pressing the switch.'],
	"replace 3 with 9": ["Substitute 'open drawer' with 'close microwave'.",
						 "Exchange 'open drawer' with 'close microwave'.",
						 "Swap 'open drawer' with 'close microwave'.",
						 "Replace 'open drawer' with 'close microwave'.",
						 "Switch 'open drawer' with 'close microwave'."],
	"replace 3 with 10": ["Substitute 'open drawer' with 'open box'.",
						  "'Open drawer' can be exchanged with 'open box'.",
						  "Replace 'open drawer' with the phrase 'open box'.",
						  "'Open drawer' should be replaced with 'open box'.",
						  "Use the term 'open box' instead of 'open drawer'."],
	"replace 3 with 11": ["Replace the phrase 'open drawer' with 'slide block to target'.",
						  "Use 'slide block to target' instead of 'open drawer'.",
						  "'Slide block to target' should be used instead of 'open drawer'.",
						  "The instruction 'open drawer' can be replaced with 'slide block to target'.",
						  "Replace the command 'open drawer' with 'slide block to target'."],
	"replace 4 with 0": ["Substitute 'close drawer' with 'open door'.",
						 "Exchange the phrase 'close drawer' to 'open door'.",
						 "Replace 'close drawer' with 'open door'.",
						 "Substitute the phrase 'close drawer' with 'open door'.",
						 "Exchange 'close drawer' for 'open door'."],
	"replace 4 with 1": ["Substitute 'close drawer' with 'close door'.",
						 "Replace 'close drawer' with 'close door'.",
						 "'Close drawer' should be changed to 'close door'.",
						 "Exchange 'close drawer' for 'close door'.",
						 "Use 'close door' instead of 'close drawer'."],
	"replace 4 with 2": ["Substitute 'close drawer' with 'close fridge'.",
						 "Change 'close drawer' to 'close fridge'.",
						 "Replace 'close drawer' with 'close fridge'.",
						 "Exchange 'close drawer' for 'close fridge'.",
						 "Substitute the phrase 'close drawer' with 'close fridge'."],
	"replace 4 with 3": ['Substitute "open drawer" for "close drawer".',
						 'Replace "close drawer" with "open drawer".',
						 'Swap "close drawer" for "open drawer".',
						 'Exchange "close drawer" with "open drawer".',
						 'Substitute the command "open drawer" for "close drawer".'],
	"replace 4 with 5": ["Substitute 'close drawer' with 'lamp off'.",
						 "'Lamp off' is the new term for 'close drawer'.",
						 "Use 'lamp off' instead of 'close drawer'.",
						 "Replace the phrase 'close drawer' with 'lamp off'.",
						 "The new instruction is to 'lamp off', not 'close drawer'."],
	"replace 4 with 6": ["Substitute 'close drawer' with 'push button'",
						 "'Push button' is the new expression for 'close drawer'",
						 "'Push button' replaces 'close drawer'",
						 "'Close drawer' is now 'push button'",
						 "'Push button' should be used instead of 'close drawer'."],
	"replace 4 with 7": ["Turn on the lamp instead of closing the drawer.",
						 "Exchange the action of 'close drawer' with 'lamp on'.",
						 "Instead of closing the drawer, switch on the lamp.",
						 "Replace the action of closing the drawer with switching the lamp on.",
						 "Choose to turn on the lamp instead of closing the drawer."],
	"replace 4 with 8": ["Substitute 'close drawer' with 'press switch'.",
						 "Replace the instruction 'close drawer' with 'press switch'.",
						 "Switch out 'close drawer' with 'press switch'.",
						 "Use 'press switch' instead of 'close drawer'.",
						 "Replace the phrase 'close drawer' with 'press switch'."],
	"replace 4 with 9": ["Substitute 'close drawer' with 'close microwave'.",
						 "'Close drawer' should be replaced with 'close microwave'.",
						 "Exchange 'close drawer' for 'close microwave'.",
						 "Switch 'close drawer' to 'close microwave'.",
						 "Replace 'close drawer' by 'close microwave'."],
	"replace 4 with 10": ['Substitute "close drawer" with "open box".',
						  'Exchange the phrase "close drawer" for "open box".',
						  'Replace the words "close drawer" with "open box".',
						  'Switch out "close drawer" for "open box".', 'Use "open box" instead of "close drawer".'],
	"replace 4 with 11": ["Substitute 'close drawer' with 'slide block to target'.",
						  "Exchange 'close drawer' with 'slide block to target'",
						  "Replace the phrase 'close drawer' with 'slide block to target.'",
						  "Use the expression 'slide block to target' instead of 'close drawer'.",
						  "Transform 'close drawer' to 'slide block to target'."
						  ],
	"replace 5 with 0": ["Change 'lamp off' to 'open door'.",
						 "Exchange 'lamp off' for 'open door'.",
						 "Substitute 'lamp off' with 'open door'.",
						 "Replace the phrase 'lamp off' with 'open door'.",
						 "Transform 'lamp off' into 'open door'."],
	"replace 5 with 1": ['Use "close door" in place of "lamp off".',
						 'Replace "lamp off" with "close door"',
						 'Substitute "close door" for "lamp off".',
						 'Change "lamp off" to "close door".',
						 'Exchange "lamp off" with "close door".'],
	"replace 5 with 2": ["Substitute 'lamp off' with 'close fridge'.",
						 "Exchange the phrase 'lamp off' with 'close fridge'.",
						 "'Close fridge' should be used instead of 'lamp off'.",
						 "Replace 'lamp off' with the phrase 'close fridge'.",
						 "The phrase 'close fridge' is to be used in place of 'lamp off'."],
	"replace 5 with 3": ['Substitute "lamp off" with "open drawer".',
						 'Swap "lamp off" for "open drawer".',
						 'Exchange "lamp off" with "open drawer".',
						 'Replace "lamp off" with "open drawer".',
						 'Switch "lamp off" to "open drawer".'
						 ],
	"replace 5 with 4": ['Substitute "lamp off" with "close drawer"',
						 'Replace the phrase "lamp off" with "close drawer"',
						 "Exchange 'lamp off' for 'close drawer'",
						 "Switch out 'lamp off' and instead use 'close drawer'",
						 "Use 'close drawer' instead of 'lamp off'."],
	"replace 5 with 6": ['Substitute "push button" for "lamp off".',
						 'Replace the phrase "lamp off" with "push button".',
						 'Exchange "lamp off" with "push button".',
						 'Transform "lamp off" into "push button".',
						 'Use "push button" instead of "lamp off".'],
	"replace 5 with 7": ["Turn on the lamp instead of turning it off.",
						 "Replace 'lamp off' with 'lamp on'.",
						 "Alter the command to 'lamp on' instead of 'lamp off'.",
						 "Instead of switching the lamp off, switch it on instead.",
						 "Change the instruction from 'lamp off' to 'lamp on'."],
	"replace 5 with 8": ['Switch the lamp off by pressing the button.',
						 'To turn off the lamp, simply press the switch.',
						 'Activate the switch to turn off the lamp.',
						 'Depress the switch to turn off the lamp.',
						 'Pressing the switch will result in the lamp turning off.'],
	"replace 5 with 9": ['Switch off the lamp and use the microwave.',
						 'Use the microwave instead of turning off the lamp.',
						 'Replace the act of turning off the lamp with using the microwave.',
						 'Trade turning off the lamp for using the microwave.',
						 'Substitute "switching off the lamp" with "closing the microwave"'],
	"replace 5 with 10": ['Substitute "lamp off" with "open box".',
						  'Replace the phrase "lamp off" with "open box".',
						  'Switch out "lamp off" for "open box".',
						  'Exchange the term "lamp off" for "open box".',
						  'Replace "lamp off" with the phrase "open box".'],
	"replace 5 with 11": ["Substitute 'turn off lamp' with 'move block to the desired location'.",
						  "Replace 'switch off lamp' with 'slide the block to the intended position'.",
						  "Exchange 'turn the lamp off' with 'move the block to the designated spot'.",
						  "Swap out 'power down the lamp' with 'place the block at the target'.",
						  "Substitute 'stop the lamp from working' with 'move the block to the appropriate location'."],
	"replace 6 with 0": ["Substitute 'push button' with 'open door'.",
						 "Exchange 'push button' for 'open door'.",
						 "Replace the action of 'push button' with 'open door'.",
						 "Transform 'push button' into 'open door'.",
						 "Swap out 'push button' for 'open door'."],
	"replace 6 with 1": ["Substitute 'push button' with 'close door'.",
						 "Exchange 'push button' with 'close door'.",
						 "Replace the phrase 'push button' with 'close door'.",
						 "Use 'close door' instead of 'push button'.",
						 "Replace 'push button' with the words 'close door'."],
	"replace 6 with 2": ["Substitute 'push button' with 'close fridge'.",
						 "Swap 'push button' for 'close fridge'.",
						 "Replace 'push button' with 'close fridge'.",
						 "Exchange 'push button' with 'close fridge'.",
						 "Use 'close fridge' instead of 'push button'."],
	"replace 6 with 3": ["Instead of using 'push button', try 'open drawer'.",
						 "'Open drawer' can be used instead of 'push button'.",
						 "'Push button' can be replaced with 'open drawer'.",
						 "'Open drawer' can be substituted for 'push button'.",
						 "Use 'open drawer' instead of 'push button'."],
	"replace 6 with 4": ["Substitute 'push button' with 'close drawer'.",
						 "Exchange 'push button' with 'close drawer'.",
						 "Replace 'push button' with 'close drawer'.",
						 "Switch 'push button' with 'close drawer'.",
						 "Use 'close drawer' instead of 'push button'."],
	"replace 6 with 5": ['Turn off the lamp using the button.',
						 'Deactivate the lamp by pressing the button.',
						 'Use the button to switch off the lamp.',
						 'The lamp can be turned off by pressing the button.',
						 'Press the button to turn off the lamp.'
						 ],
	"replace 6 with 7": ['Substitute "push button" with "lamp on".',
						 'Replace the phrase "push button" with the phrase "lamp on".',
						 "Use 'lamp on' instead of 'push button'.",
						 "Exchange 'push button' with 'lamp on'.",
						 "Switch out 'push button' for 'lamp on'."],
	"replace 6 with 8":
		["Substitute 'push button' with 'press switch'.",
		 "Replace 'push button' with 'press switch'.",
		 "Change 'push button' to 'press switch'.",
		 "Switch 'push button' with 'press switch'.",
		 "Use 'press switch' instead of 'push button'."],
	"replace 6 with 9": ["Substitute 'push button' with 'close microwave'.",
						 "Exchange 'push button' for 'close microwave'.",
						 "Replace the phrase 'push button' with 'close microwave'.",
						 "Swap out 'push button' with 'close microwave'.",
						 "Alter 'push button' to be 'close microwave'."],
	"replace 6 with 10": ["Substitute 'push button' with 'open box'",
						  "Replace 'push button' with 'open box'",
						  "Exchange 'push button' for 'open box'",
						  "Switch 'push button' to 'open box'",
						  "Use 'open box' instead of 'push button'"],
	"replace 6 with 11": ['Substitute the phrase "push button" with "slide block to target".',
						  'Exchange "push button" with "slide block to target".',
						  'Replace "push button" with "slide block to target".',
						  'Substitute "push button" with "slide block to target".',
						  'Change "push button" to "slide block to target".'],
	"replace 7 with 0": ["Substitute 'lamp on' with 'open door'",
						 "'Open door' instead of 'lamp on'",
						 "Swap 'lamp on' with 'open door'",
						 "Replace 'lamp on' with 'open door'",
						 "Exchange 'lamp on' with 'open door'"],
	"replace 7 with 1": ["Change 'lamp on' to 'close door'.",
						 "Substitute 'lamp on' with 'close door'.",
						 "Replace 'lamp on' for 'close door'.",
						 "Exchange 'lamp on' with 'close door'.",
						 "Swap out 'lamp on' for 'close door'."],
	"replace 7 with 2": ['Substitute "lamp on" with "close fridge".', 'Exchange "lamp on" for "close fridge".',
						 'Replace the phrase "lamp on" with "close fridge".', 'Swap "lamp on" for "close fridge".',
						 'Change "lamp on" to "close fridge".'],
	"replace 7 with 3": ["Substitute 'lamp on'  with 'open drawer'",
						 "'open drawer' should replace 'lamp on'",
						 "'lamp on' ought to be exchanged with 'open drawer'",
						 "Exchange 'lamp on' to 'open drawer'",
						 "Swap 'lamp on' for 'open drawer'"],
	"replace 7 with 4": ["Change 'lamp on' to 'close drawer'.",
						 "Substitute 'lamp on' with 'close drawer'.",
						 "Swap 'lamp on' for 'close drawer'.",
						 "Exchange 'lamp on' with 'close drawer'.",
						 "Replace 'lamp on' with 'close drawer'."],
	"replace 7 with 5": ['Change the state of the lamp from on to off.',
						 'Switch the lamp from on to off.',
						 'Alter the condition of the lamp to off from on.',
						 'Convert the status of the lamp from on to off.',
						 'Substitute the phrase "lamp on" with "lamp off".'],
	"replace 7 with 6": ['Substitute the term \'lamp on\' with \'push button\'.',
						 'Exchange the phrase \'lamp on\' with \'push button\'.',
						 'Replace \'lamp on\' with \'push button\'.', 'Swap \'lamp on\' with \'push button\'.',
						 'Substitute the expression \'lamp on\' with \'push button\'.'],
	"replace 7 with 8": ["Substitute 'lamp on' with 'press switch'.",
						 "Exchange 'lamp on' for 'press switch'.",
						 "Switch 'lamp on' to 'press switch'.",
						 "Replace the phrase 'lamp on' with 'press switch'.",
						 "Transform 'lamp on' to 'press switch'."],
	"replace 7 with 9": ["Substitute 'turn off the lamp' for 'shut the microwave.'",
						 "Exchange the phrase 'lamp on' for 'shut off the microwave.'",
						 "Replace 'lamp on' with 'close microwave.'",
						 "Switch 'turn on lamp' with 'close microwave.'",
						 "Substitute 'start the lamp' for 'stop the microwave.'"],
	"replace 7 with 10": ["Substitute 'lamp on' with 'open box'",
						  "Transform 'lamp on' into 'open box'",
						  "Exchange 'lamp on' for 'open box'",
						  "Replace 'lamp on' with 'open box'",
						  "Switch 'lamp on' to 'open box'"],
	"replace 7 with 11": ["Substitute 'lamp on' with 'slide block to target'",
						  "Replace 'lamp on' with 'slide block to target'",
						  "'lamp on' must be replaced with 'slide block to target'",
						  "'slide block to target' can be used instead of 'lamp on'",
						  "Use 'slide block to target' in place of 'lamp on'"],
	"replace 8 with 0": ["Substitute 'press switch' with 'open door'",
						 "Replace the phrase 'press switch' with 'open door'",
						 "Exchange the words 'press switch' with 'open door'",
						 "Swap out 'press switch' for 'open door'",
						 "Transform 'press switch' to 'open door'"],
	"replace 8 with 1": ["Substitute 'press switch' with 'close door'",
						 "Exchange 'press switch' with 'close door'",
						 "Replace 'press switch' with 'close door'",
						 "Use 'close door' instead of 'press switch'",
						 "Substitute the action of 'pressing switch' with 'closing door'"],
	"replace 8 with 2": ["Substitute 'press switch' with 'close fridge'.",
						 "Replace the term 'press switch' with 'close fridge'.",
						 "Exchange 'press switch' for 'close fridge'.",
						 "Swap out 'press switch' with 'close fridge'.",
						 "Substitute the phrase 'press switch' with 'close fridge'."],
	"replace 8 with 3": ["Replace 'press switch' with 'open drawer'.",
						 "Use 'open drawer' instead of 'press switch'.",
						 "Swap 'press switch' with 'open drawer'.",
						 "Employ 'open drawer' as a substitute for 'press switch'.",
						 "Exchange 'press switch' for 'open drawer'."],
	"replace 8 with 4": ["Substitute 'press switch' for 'close drawer'.",
						 "Use 'close drawer' instead of 'press switch'.",
						 "Exchange 'press switch' with 'close drawer'.",
						 "Replace 'press switch' by 'close drawer'.",
						 "'close drawer' should be used instead of 'press switch'."],
	"replace 8 with 5": ['Turn off the lamp by pressing the switch.',
						 'Using the switch, turn off the lamp.',
						 'To switch off the lamp, press the button.',
						 'Pressing the switch will turn the lamp off.',
						 'Make the lamp go off by pressing the switch.'],
	"replace 8 with 6": ["Substitute 'press switch' with 'push button'.",
						 "Exchange 'press switch' with 'push button'.",
						 "Replace the phrase 'press switch' with 'push button'.",
						 "Use 'push button' instead of 'press switch'.",
						 "Switch out 'press switch' with 'push button'."],
	"replace 8 with 7": ["Switch the lamp on", "Turn on the lamp", "Activate the lamp", "Switch on the light",
						 "Illuminate the room with the lamp"],
	"replace 8 with 9": ["Substitute 'press switch' with 'close microwave'.",
						 "Replace the phrase 'press switch' with 'close microwave'.",
						 "Exchange 'press switch' for 'close microwave'.",
						 "Swap out 'press switch' for 'close microwave'.",
						 "Change 'press switch' to 'close microwave'."],
	"replace 8 with 10": ['Substitute "press switch" with "open box".',
						  'Replace the phrase "press switch" with "open box".',
						  'Exchange "press switch" with "open box".',
						  'Substitute the term "press switch" for "open box".',
						  'Replace "press switch" with "open box".'],
	"replace 8 with 11": ["Substitute 'press switch' with 'slide block to target'.",
						  "Exchange 'press switch' for 'slide block to target'.",
						  "Replace the phrase 'press switch' with 'slide block to target'.",
						  "Swap 'press switch' with 'slide block to target'.",
						  "Transform 'press switch' to 'slide block to target'."],
	"replace 9 with 0": ["Substitute 'open the door' for 'shut the microwave'.",
						 "Exchange 'open the door' with 'close the microwave'.",
						 "Replace 'close the microwave' with 'open the door'.",
						 "Switch 'shut the microwave' for 'open the door'.",
						 "Use 'open the door' instead of 'close microwave'."],
	"replace 9 with 1": ["Replace the phrase 'close microwave' with 'close door'.",
						 "Exchange the words 'close microwave' with 'close door'.",
						 "Substitute 'close microwave' with 'close door'.",
						 "Replace 'close microwave' with the words 'close door'.",
						 "Change 'close microwave' to 'close door'."],
	"replace 9 with 2": ["Substitute 'close microwave' with 'close fridge'.",
						 "Replace the phrase 'close microwave' with 'close fridge'.",
						 "'Close fridge' should replace 'close microwave'.",
						 "Change 'close microwave' to 'close fridge'.",
						 "Switch 'close microwave' with 'close fridge'."],
	"replace 9 with 3": ["Substitute 'open drawer' for 'close microwave'.",
						 "Change 'close microwave' to 'open drawer'.",
						 "Replace 'close microwave' with 'open drawer'.",
						 "Exchange 'close microwave' with 'open drawer'.",
						 "Switch 'close microwave' to 'open drawer'."],
	"replace 9 with 4": ["Replace the phrase 'close microwave' with 'close drawer'.",
						 "Substitute 'close microwave' with 'close drawer'.",
						 "Exchange 'close microwave' with 'close drawer'.",
						 "Swap out 'close microwave' for 'close drawer'.",
						 "Replace the words 'close microwave' with 'close drawer'."
						 ],
	"replace 9 with 5": ['Turn off the lamp instead of closing the microwave.',
						 'Instead of closing the microwave, switch off the lamp.',
						 'Swap out the instruction to "close microwave" for "turn off lamp".',
						 'Replace "close microwave" with "turn off lamp".',
						 'Substitute "microwave close" with "lamp off" in the set of instructions.'],
	"replace 9 with 6": ['Press the button instead of closing the microwave.',
						 'Use the button instead of shutting the microwave.',
						 'Switch to pushing the button instead of closing the microwave.',
						 'Instead of closing the microwave, simply push the button.',
						 'The alternative to closing the microwave is to push the button.'],
	"replace 9 with 7": ["Substitute 'close microwave' with 'lamp on'.",
						 "Change 'close microwave' to 'lamp on'.",
						 "Replace 'close microwave' with 'turn on lamp'.",
						 "'Close microwave' should be replaced with 'lamp on'.",
						 "'Close the microwave' must be substituted with 'turn on the lamp'."],
	"replace 9 with 8": ["Substitute 'close microwave' with 'press switch'.",
						 "Exchange 'close microwave' with 'press switch'.",
						 "Replace the phrase 'close microwave' with 'press switch'.",
						 "Switch 'close microwave' with 'press switch'.",
						 "Use 'press switch' instead of 'close microwave'."],
	"replace 9 with 10": ["Substitute 'open box' for 'close microwave'.",
						  "Replace 'close microwave' with 'open box'.",
						  "Exchange 'close microwave' for 'open box'.",
						  "Switch 'close microwave' to 'open box'.",
						  "Substitute 'open box' in place of 'close microwave'."],
	"replace 9 with 11": ['Substitute "close microwave" with "slide block to target"',
						  'Replace the phrase "close microwave" with "slide block to target"',
						  "Exchange 'close microwave' with 'slide block to target'",
						  "Transform the expression 'close microwave' to 'slide block to target'",
						  "Convert 'close microwave' to 'slide block to target'"],
	"replace 10 with 0": ["Replace the phrase 'open box' with 'open door'.",
						  "Substitute 'open box' with 'open door'.",
						  "Replace 'open box' with the phrase 'open door'.",
						  "Exchange 'open box' for 'open door'.",
						  "Swap the phrase 'open box' with 'open door'."],
	"replace 10 with 1": ["Change the phrase 'open box' to 'close door'",
						  "Substitute 'open box' with 'close door'",
						  "Replace 'open box' with 'close door'",
						  "Exchange 'open box' for 'close door'",
						  "Switch 'open box' for 'close door'"],
	"replace 10 with 2": ["Substitute 'open box' with 'close fridge'",
						  "Replace the phrase 'open box' with 'close fridge'",
						  "Change the words 'open box' to 'close fridge'",
						  "Swap 'open box' for 'close fridge'",
						  "Exchange 'open box' for 'close fridge'"],
	"replace 10 with 3": ['Substitute \'open box\' with \'open drawer\'',
						  'Change \'open box\' to \'open drawer\'',
						  'Exchange \'open box\' for \'open drawer\'',
						  'Replace \'open box\' with \'open drawer\'',
						  'Use \'open drawer\' instead of \'open box\''],
	"replace 10 with 4": ['Substitute \'open box\' with \'close drawer\'',
						  'Swap \'open box\' for \'close drawer\'',
						  'Replace \'open box\' with \'close drawer\'',
						  'Exchange \'open box\' for \'close drawer\'',
						  'Convert \'open box\' to \'close drawer\'', ],
	"replace 10 with 5": ["Substitute 'open box' with 'lamp off'",
						  "Switch 'open box' with 'lamp off'",
						  "Replace the phrase 'open box' with 'lamp off'",
						  "Exchange 'open box' with 'lamp off'",
						  "Use 'lamp off' instead of 'open box'"],
	"replace 10 with 6": ['Substitute the phrase "open box" with "press button."',
						  'Use "push button" in place of "open box."',
						  "Exchange 'open box' with 'push button'.",
						  "The phrase 'push button' should be used instead of 'open box'.",
						  "Replace 'open box' with 'press button'."],
	"replace 10 with 7": ["Substitute 'open box' with 'lamp on'",
						  "Exchange 'open box' for 'lamp on'",
						  "Replace the phrase 'open box' with 'lamp on'",
						  "Swap out 'open box' with 'lamp on'",
						  "Use 'lamp on' instead of 'open box'"],
	"replace 10 with 8": ["Substitute the term 'open box' with 'press switch'.",
						  "Exchange the phrase 'open box' for 'press switch'.",
						  "Replace 'open box' with 'press switch'.",
						  "Use 'press switch' instead of 'open box'.",
						  "Switch 'open box' to 'press switch'."],
	"replace 10 with 9": ['substitute "open box" with "close microwave"', 'change "open box" to "close microwave"',
						  'use "close microwave" instead of "open box"',
						  'replace "open box" with "close microwave"', 'swap out "open box" for "close microwave"'],
	"replace 10 with 11": ['Substitute "open box" with "slide block to target".',
						   'Use "slide block to target" instead of "open box".',
						   'Replace "open box" with "slide block to target".',
						   'Change "open box" to "slide block to target".',
						   'Swap "open box" with "slide block to target".'
						   ],
	"replace 11 with 0": ["Substitute 'slide block to target' with 'open door'.",
						  "Replace the phrase 'slide block to target' with 'open door'.",
						  "Exchange 'slide block to target' for 'open door'.",
						  "Switch 'slide block to target' with 'open door'.",
						  "Swap out the term 'slide block to target' for 'open door'."],
	"replace 11 with 1": ['Substitute "slide block to target" with "close door".',
						  'Use "close door" instead of "slide block to target".',
						  'Replace "slide block to target" with "close door".',
						  'Exchange "slide block to target" with "close door".',
						  'Switch "slide block to target" to "close door".'],
	"replace 11 with 2": ["Substitute 'slide block to target' for 'close fridge'",
						  "'Close fridge' should replace 'slide block to target'",
						  "The new command is 'close fridge' instead of 'slide block to target'",
						  "'Close fridge' is the new instruction instead of 'slide block to target'",
						  "Replace 'slide block to target' with 'close fridge' as the new command"],
	"replace 11 with 3": ["Change 'slide block to target' to 'open drawer'",
						  "Replace 'slide block to target' with 'open drawer'",
						  "Substitute 'slide block to target' for 'open drawer'",
						  "Exchange 'slide block to target' with 'open drawer'",
						  "Convert 'slide block to target' into 'open drawer'"],
	"replace 11 with 4": ["Substitute 'slide block to target' with 'close drawer'",
						  "Replace 'slide block to target' with 'close drawer'",
						  "'Close drawer' should be used instead of 'slide block to target'",
						  "'Slide block to target' ought to be replaced by 'close drawer'",
						  "Use 'close drawer' instead of 'slide block to target'"],
	"replace 11 with 5": ["Change 'slide block to target' to 'lamp off'",
						  "Substitute 'slide block to target' with 'lamp off'",
						  "Replace 'slide block to target' with 'lamp off'",
						  "Exchange 'slide block to target' for 'lamp off'",
						  "Switch 'slide block to target' to 'lamp off'"],
	"replace 11 with 6": ["Replace the phrase 'slide block to target' with 'push button'.",
						  "Substitute 'push button' for 'slide block to target'.",
						  "Exchange 'slide block to target' with 'push button'.",
						  "Replace 'slide block to target' with the term 'push button'.",
						  "Use 'push button' instead of 'slide block to target'."],
	"replace 11 with 7": ["Substitute 'slide block to target' with 'lamp on'.",
						  "Exchange 'slide block to target' with 'lamp on'.",
						  "Replace 'slide block to target' with 'lamp on'.",
						  "Swap 'slide block to target' with 'lamp on'.",
						  "Use 'lamp on' in lieu of 'slide block to target'."],
	"replace 11 with 8": ["Instead of sliding block, push button to reach goal",
						  "Instead of manipulating the block on its path, press the switch",
						  "Substitute the action of sliding the block with pressing the switch",
						  "Swap from sliding the block to hitting or pressing the switch",
						  "Rather than sliding the block, activate the switch by pressing it"],
	"replace 11 with 9": ["Swap 'slide block to target' with 'close the microwave'",
						  "Change 'slide block to target' to 'close the microwave'",
						  "Substitute 'slide block to target' for 'close the microwave'",
						  "Replace 'slide block to target' with 'shut the microwave'",
						  "Exchange 'slide block to target' with 'turn off the microwave'"],
	"replace 11 with 10": ["Replace the phrase 'slide block to target' with 'open box'.",
						   "Substitute 'open box' for 'slide block to target'.",
						   "Exchange 'slide block to target' with 'open box'.",
						   "Use 'open box' instead of 'slide block to target'.",
						   "Replace the words 'slide block to target' with 'open box'."],

}
NON_FUNCTIONALITIES_VARIATIONS = {"weight": ["objects weight"]}
