import pickle
from itertools import permutations
from pathlib import Path

import torch as th
from transformers import BertTokenizer, BertModel

if __name__ == "__main__":

	# === Hyper parameters
	save_dir = "/home/jsw7460/mnt/comde_datasets/language_embeddings/bert_mappings/language_guidance/"
	topic = "kitchen_seq_rev_rep"
	main_texts = ["sequential", "reverse"]

	skills_idxs = [str(i) for i in range(7)]

	nC2 = permutations(skills_idxs, 2)
	for (i, j) in nC2:
		fmt = f"replace {i} with {j}"
		main_texts.append(fmt)

	# text_variations: Key: main_texts // value: variations of main_texts

	texts_variations = {
		"sequential": ["Execute these in a particular order.", "Complete these one after the other.",
					   "Do these tasks in a specific order.", "Carry out these actions sequentially.",
					   "Perform these steps in order.", "Follow these instructions in sequence.",
					   "Undertake these tasks in a particular sequence.",
					   "Accomplish these actions in a predetermined order.",
					   "Execute these procedures in the correct order.", "Work through these steps in sequence.",
					   "Perform these actions in a specific order.", "Complete these tasks in an ordered manner.",
					   "Undertake these steps sequentially.", "Carry out these instructions in order.",
					   "Follow these steps in a particular sequence.", "Do these actions in a predetermined order.",
					   "Accomplish these tasks in sequence.", "Execute these in a prescribed order.",
					   "Perform these tasks consecutively.", "Complete these tasks one by one.",
					   "Carry out these tasks in a specific order.", "Follow these procedures sequentially.",
					   "Do these in a particular order.", "Undertake these tasks in a specific order.",
					   "Work through these actions in sequence.", "Perform these tasks in a particular order.",
					   "Complete these in a specific sequence.", "Follow these instructions sequentially.",
					   "Carry out these actions one after the other.", "Do these steps in a particular order.",
					   "Undertake these procedures in sequence.", "Accomplish these tasks in an ordered manner.",
					   "Execute these in the correct order.", "Perform these actions consecutively.",
					   "Complete these steps in a specific order.", "Carry out these tasks in the correct order.",
					   "Follow these steps one by one.", "Undertake these actions in sequence.",
					   "Work through these tasks in order.", "Perform these in a particular sequence.",
					   "Complete these procedures one after the other.", "Do these in a specific order.",
					   "Carry out these steps sequentially.", "Follow these tasks in a predetermined order.",
					   "Undertake these in a specific sequence.", "Accomplish these actions consecutively.",
					   "Execute these tasks in a particular order.", "Perform these instructions in sequence.",
					   "Complete these in the correct order.", "Carry out these steps one after another."],
		"reverse": ["Do these in the opposite order.", "Carry out these in reverse sequence.",
					"Execute these in reverse order.", "Perform these in a reversed sequence.",
					"Complete these in the reverse order.", "Undertake these in the reverse order.",
					"Work through these in reverse order.", "Carry out these backwards.",
					"Execute these in the opposite sequence.", "Perform these in the inverse order.",
					"Do these in the reverse sequence.", "Complete these in reverse order.",
					"Undertake these backwards.", "Work through these in the opposite order.",
					"Carry out these in the opposite order.", "Execute these in the reverse order.",
					"Perform these backwards.", "Do these in the opposite sequence.",
					"Complete these in an inverted order.", "Undertake these in an inverse sequence.",
					"Work through these in the reverse order.", "Carry out these in a backward order.",
					"Execute these backwards.", "Perform these in the opposite order.",
					"Do these in a backward sequence.", "Complete these in the inverse order.",
					"Undertake these in the opposite order.", "Work through these backwards.",
					"Carry out these in the inverse order.", "Execute these in an inverted sequence.",
					"Perform these in the contrary order.", "Do these backwards.", "Complete these in a reverse order.",
					"Undertake these in a reversed sequence.", "Work through these in the inverted order.",
					"Carry out these in an opposite sequence.", "Execute these in a reversed order.",
					"Perform these in the contrary sequence.", "Do these in the inverted order.",
					"Complete these in a backward manner.", "Undertake these in a reverse order.",
					"Work through these in the reversed sequence.", "Carry out these in the opposite sequence.",
					"Execute these in an inverse order.", "Perform these in the backward sequence.",
					"Do these in the contrary order.", "Complete these in a reverted order.",
					"Undertake these in a backward sequence.", "Work through these in a reverse order.",
					"Carry out these in the inverted order.", "Execute these in an opposite sequence.",
					"Perform these in the opposite manner."],

		"replace 0 with 1": [
			'Replace the top burner with the bottom burner.',
			'Swap the positions of the top and bottom burners.',
			'Exchange the bottom and top burners.',
			'Place the top burner where the bottom burner is and vice versa.',
			'Put the bottom burner on top and move the top burner to the bottom.',
			'Move the top burner down and the bottom burner up.',
			'Reorder the burners so that the bottom one becomes the top one.',
			'Rearrange the burners by interchanging their positions.',
			'Switch the positions of the bottom and top burners.'
		],
		"replace 0 with 2": [
			'Exchange the bottom burner with the light switch.',
			'Put the light switch where the bottom burner is and vice versa.',
			'Swap the positions of the bottom burner and the light switch.',
			'Move the bottom burner to where the light switch is and move the light switch to where the bottom burner is.',
			'Rearrange the bottom burner and the light switch.',
			'Switch the light switch with the bottom burner.',
			'Replace the position of the light switch with the bottom burner.',
			'Interchange the bottom burner and the light switch.',
			'Place the light switch where the bottom burner is and put the bottom burner where the light switch is.'
		],
		"replace 0 with 3": [
			'Swap the positions of the bottom burner and the slide cabinet.',
			'Exchange the bottom burner with the slide cabinet.',
			'Move the bottom burner to where the slide cabinet is and move the slide cabinet to where the bottom burner is.',
			'Put the slide cabinet where the bottom burner is and vice versa.',
			'Rearrange the bottom burner and the slide cabinet.',
			'Replace the position of the slide cabinet with the bottom burner.',
			'Move the bottom burner down to the slide cabinet\'s position and the slide cabinet up to the bottom burner\'s position.',
			'Interchange the positions of the bottom burner and the slide cabinet.',
			'Swap the bottom burner and the slide cabinet.'
		],
		"replace 0 with 4": [
			'Exchange the bottom burner with the hinge cabinet.',
			'Swap the positions of the bottom burner and the hinge cabinet.',
			'Move the bottom burner to where the hinge cabinet is and move the hinge cabinet to where the bottom burner is.',
			'Put the hinge cabinet where the bottom burner is and vice versa.',
			'Rearrange the bottom burner and the hinge cabinet.',
			'Switch the hinge cabinet with the bottom burner.',
			'Place the hinge cabinet where the bottom burner is and put the bottom burner where the hinge cabinet is.',
			'Interchange the bottom burner and the hinge cabinet.',
			'Move the bottom burner down to the hinge cabinet\'s position and the hinge cabinet up to the bottom burner\'s position.'
		],
		"replace 0 with 5": [
			'Exchange the bottom burner with the microwave.',
			'Swap the positions of the bottom burner and the microwave.',
			'Move the bottom burner to where the microwave is and move the microwave to where the bottom burner is.',
			'Put the microwave where the bottom burner is and vice versa.',
			'Rearrange the bottom burner and the microwave.',
			'Switch the microwave with the bottom burner.',
			'Place the microwave where the bottom burner is and put the bottom burner where the microwave is.',
			'Interchange the bottom burner and the microwave.',
			'Move the bottom burner down to the microwave\'s position and the microwave up to the bottom burner\'s position.'
		],
		"replace 0 with 6": [
			'Exchange the bottom burner with the kettle.',
			'Swap the positions of the bottom burner and the kettle.',
			'Move the bottom burner to where the kettle is and move the kettle to where the bottom burner is.',
			'Put the kettle where the bottom burner is and vice versa.',
			'Rearrange the bottom burner and the kettle.',
			'Switch the kettle with the bottom burner.',
			'Place the kettle where the bottom burner is and put the bottom burner where the kettle is.',
			'Interchange the bottom burner and the kettle.',
			'Move the bottom burner down to the kettle\'s position and the kettle up to the bottom burner\'s position.',
			'Change the positions of the bottom burner and the kettle.',
			'Replace the bottom burner with the kettle and vice versa.'
		],
		"replace 1 with 0": [
			'Swap the positions of the top burner and the bottom burner.',
			'Exchange the top burner with the bottom burner.',
			'Move the top burner to where the bottom burner is and move the bottom burner to where the top burner is.',
			'Put the bottom burner where the top burner is and vice versa.',
			'Rearrange the top and bottom burners.',
			'Switch the top burner with the bottom burner.',
			'Place the bottom burner where the top burner is and put the top burner where the bottom burner is.',
			'Interchange the top and bottom burners.',
			'Move the top burner down to the bottom burner\'s position and the bottom burner up to the top burner\'s position.'
		],
		"replace 1 with 2": [
			'Swap the positions of the top burner and the light switch.',
			'Move the top burner to where the light switch is and move the light switch to where the top burner is.',
			'Put the light switch where the top burner is and vice versa.',
			'Rearrange the top burner and the light switch.',
			'Switch the light switch with the top burner.',
			'Place the light switch where the top burner is and put the top burner where the light switch is.',
			'Interchange the top burner and the light switch.',
			'Move the top burner down to the light switch\'s position and the light switch up to the top burner\'s position.',
			'Change the positions of the top burner and the light switch.',
			'Replace the top burner with the light switch and vice versa.',
			'Exchange the positions of the light switch and the top burner.',
			'Swap the light switch and the top burner.'
		],
		"replace 1 with 3": [
			'Swap the positions of the top burner and the slide cabinet.',
			'Move the top burner to where the slide cabinet is and move the slide cabinet to where the top burner is.',
			'Put the slide cabinet where the top burner is and vice versa.',
			'Rearrange the top burner and the slide cabinet.',
			'Switch the slide cabinet with the top burner.',
			'Place the slide cabinet where the top burner is and put the top burner where the slide cabinet is.',
			'Interchange the top burner and the slide cabinet.',
			'Move the top burner down to the slide cabinet\'s position and the slide cabinet up to the top burner\'s position.',
			'Change the positions of the top burner and the slide cabinet.',
			'Replace the top burner with the slide cabinet and vice versa.',
			'Exchange the positions of the slide cabinet and the top burner.',
			'Swap the slide cabinet and the top burner.'
		],
		"replace 1 with 4": [
			'Swap the positions of the top burner and the hinge cabinet.',
			'Move the top burner to where the hinge cabinet is and move the hinge cabinet to where the top burner is.',
			'Put the hinge cabinet where the top burner is and vice versa.',
			'Rearrange the top burner and the hinge cabinet.',
			'Switch the hinge cabinet with the top burner.',
			'Place the hinge cabinet where the top burner is and put the top burner where the hinge cabinet is.',
			'Interchange the top burner and the hinge cabinet.',
			'Move the top burner down to the hinge cabinet\'s position and the hinge cabinet up to the top burner\'s position.',
			'Change the positions of the top burner and the hinge cabinet.',
			'Replace the top burner with the hinge cabinet and vice versa.',
			'Exchange the positions of the hinge cabinet and the top burner.',
			'Swap the hinge cabinet and the top burner.'
		],
		"replace 1 with 5": [
			'Swap the positions of the top burner and the microwave.',
			'Move the top burner to where the microwave is and move the microwave to where the top burner is.',
			'Put the microwave where the top burner is and vice versa.',
			'Rearrange the top burner and the microwave.',
			'Switch the microwave with the top burner.',
			'Place the microwave where the top burner is and put the top burner where the microwave is.',
			'Interchange the top burner and the microwave.',
			'Move the top burner down to the microwave\'s position and the microwave up to the top burner\'s position.',
			'Change the positions of the top burner and the microwave.'
		],
		"replace 1 with 6": [
			'Swap the positions of the top burner and the kettle.',
			'Move the top burner to where the kettle is and move the kettle to where the top burner is.',
			'Put the kettle where the top burner is and vice versa.',
			'Rearrange the top burner and the kettle.',
			'Switch the kettle with the top burner.',
			'Place the kettle where the top burner is and put the top burner where the kettle is.',
			'Interchange the top burner and the kettle.',
			'Move the top burner down to the kettle\'s position and the kettle up to the top burner\'s position.',
			'Change the positions of the top burner and the kettle.',
			'Replace the top burner with the kettle and vice versa.',
			'Exchange the positions of the kettle and the top burner.',
			'Swap the kettle and the top burner.'
		],
		"replace 2 with 0": [
			"Swap the positions of the light switch and the bottom burner.",
			"Move the light switch to where the bottom burner is and move the bottom burner to where the light switch is.",
			"Put the bottom burner where the light switch is and vice versa.",
			"Rearrange the light switch and the bottom burner.",
			"Switch the bottom burner with the light switch.",
			"Place the bottom burner where the light switch is and put the light switch where the bottom burner is.",
			"Interchange the light switch and the bottom burner.",
			"Move the bottom burner up to the light switch's position and the light switch down to the bottom burner's position.",
			"Change the positions of the light switch and the bottom burner.",
			"Replace the light switch with the bottom burner and vice versa.",
			"Exchange the positions of the bottom burner and the light switch.",
			"Swap the light switch and the bottom burner."
		],
		"replace 2 with 1": ["Swap the positions of the light switch and the top burner.",
							 "Move the light switch to where the top burner is and move the top burner to where the light switch is.",
							 "Put the top burner where the light switch is and vice versa.",
							 "Rearrange the light switch and the top burner.",
							 "Switch the top burner with the light switch.",
							 "Place the top burner where the light switch is and put the light switch where the top burner is.",
							 "Interchange the light switch and the top burner.",
							 "Move the top burner down to the light switch's position and the light switch up to the top burner's position.",
							 "Change the positions of the light switch and the top burner.",
							 "Replace the light switch with the top burner and vice versa.",
							 "Exchange the positions of the top burner and the light switch.",
							 "Swap the light switch and the top burner."],
		"replace 2 with 3": ["Swap the positions of the light switch and the slide cabinet.",
							 "Move the light switch to where the slide cabinet is and move the slide cabinet to where the light switch is.",
							 "Put the slide cabinet where the light switch is and vice versa.",
							 "Rearrange the light switch and the slide cabinet.",
							 "Switch the slide cabinet with the light switch.",
							 "Place the slide cabinet where the light switch is and put the light switch where the slide cabinet is.",
							 "Interchange the light switch and the slide cabinet.",
							 "Move the slide cabinet up to the light switch's position and the light switch down to the slide cabinet's position.",
							 "Change the positions of the light switch and the slide cabinet.",
							 "Replace the light switch with the slide cabinet and vice versa.",
							 "Exchange the positions of the slide cabinet and the light switch.",
							 "Swap the slide cabinet and the light switch."],
		"replace 2 with 4": ["Swap the positions of the light switch and the hinge cabinet.",
							 "Move the light switch to where the hinge cabinet is and move the hinge cabinet to where the light switch is.",
							 "Put the hinge cabinet where the light switch is and vice versa.",
							 "Rearrange the light switch and the hinge cabinet.",
							 "Switch the hinge cabinet with the light switch.",
							 "Place the hinge cabinet where the light switch is and put the light switch where the hinge cabinet is.",
							 "Interchange the light switch and the hinge cabinet.",
							 "Move the hinge cabinet up to the light switch's position and the light switch down to the hinge cabinet's position.",
							 "Change the positions of the light switch and the hinge cabinet.",
							 "Replace the light switch with the hinge cabinet and vice versa.",
							 "Exchange the positions of the hinge cabinet and the light switch.",
							 "Swap the light switch and the hinge cabinet."],
		"replace 2 with 5": ['Swap the positions of the light switch and the microwave.',
							 'Move the light switch to where the microwave is and move the microwave to where the light switch is.',
							 'Put the microwave where the light switch is and vice versa.',
							 'Rearrange the light switch and the microwave.',
							 'Switch the microwave with the light switch.',
							 'Place the microwave where the light switch is and put the light switch where the microwave is.',
							 'Interchange the light switch and the microwave.',
							 'Move the microwave up to the light switchs position and the light switch down to the microwaves position.',
							 'Change the positions of the light switch and the microwave.',
							 'Replace the light switch with the microwave and vice versa.',
							 'Exchange the positions of the microwave and the light switch.',
							 'Swap the light switch and the microwave.'],
		"replace 2 with 6": ['Swap the positions of the light switch and the kettle.',
							 'Move the light switch to where the kettle is and move the kettle to where the light switch is.',
							 'Put the kettle where the light switch is and vice versa.',
							 'Rearrange the light switch and the kettle.', 'Switch the kettle with the light switch.',
							 'Place the kettle where the light switch is and put the light switch where the kettle is.',
							 'Interchange the light switch and the kettle.',
							 'Move the kettle up to the light switchs and position and the light switch down to the kettles position.',
							 'Change the positions of the light switch and the kettle.',
							 'Replace the light switch with the kettle and vice versa.',
							 'Exchange the positions of the kettle and the light switch.',
							 'Swap the light switch and the kettle.'],
		"replace 3 with 0": ["Swap the positions of the slide cabinet and the bottom burner.",
							 "Move the slide cabinet to where the bottom burner is and move the bottom burner to where the slide cabinet is.",
							 "Put the bottom burner where the slide cabinet is and vice versa.",
							 "Rearrange the slide cabinet and the bottom burner.",
							 "Switch the bottom burner with the slide cabinet.",
							 "Place the bottom burner where the slide cabinet is and put the slide cabinet where the bottom burner is.",
							 "Interchange the slide cabinet and the bottom burner.",
							 "Move the bottom burner up to the slide cabinet's position and the slide cabinet down to the bottom burner's position.",
							 "Change the positions of the slide cabinet and the bottom burner.",
							 "Replace the slide cabinet with the bottom burner and vice versa.",
							 "Exchange the positions of the bottom burner and the slide cabinet.",
							 "Swap the slide cabinet and the bottom burner."],
		"replace 3 with 1": [
			"Swap the positions of the slide cabinet and the top burner.",
			"Move the slide cabinet to where the top burner is and move the top burner to where the slide cabinet is.",
			"Put the top burner where the slide cabinet is and vice versa.",
			"Rearrange the slide cabinet and the top burner.",
			"Switch the top burner with the slide cabinet.",
			"Place the top burner where the slide cabinet is and put the slide cabinet where the top burner is.",
			"Interchange the slide cabinet and the top burner.",
			"Move the top burner down to the slide cabinet's position and the slide cabinet up to the top burner's position.",
			"Change the positions of the slide cabinet and the top burner.",
			"Replace the slide cabinet with the top burner and vice versa.",
			"Exchange the positions of the top burner and the slide cabinet.",
			"Swap the slide cabinet and the top burner."
		],
		"replace 3 with 2": ["Swap the positions of the slide cabinet and the light switch.",
							 "Move the slide cabinet to where the light switch is and move the light switch to where the slide cabinet is.",
							 "Put the light switch where the slide cabinet is and vice versa.",
							 "Rearrange the slide cabinet and the light switch.",
							 "Switch the light switch with the slide cabinet.",
							 "Place the light switch where the slide cabinet is and put the slide cabinet where the light switch is.",
							 "Interchange the slide cabinet and the light switch.",
							 "Move the light switch down to the slide cabinet's position and the slide cabinet up to the light switch's position.",
							 "Change the positions of the slide cabinet and the light switch.",
							 "Replace the slide cabinet with the light switch and vice versa.",
							 "Exchange the positions of the light switch and the slide cabinet.",
							 "Swap the slide cabinet and the light switch."],
		"replace 3 with 4": ["Swap the positions of the slide cabinet and the hinge cabinet.",
							 "Move the slide cabinet to where the hinge cabinet is and move the hinge cabinet to where the slide cabinet is.",
							 "Put the hinge cabinet where the slide cabinet is and vice versa.",
							 "Rearrange the slide cabinet and the hinge cabinet.",
							 "Switch the hinge cabinet with the slide cabinet.",
							 "Place the hinge cabinet where the slide cabinet is and put the slide cabinet where the hinge cabinet is.",
							 "Interchange the slide cabinet and the hinge cabinet.",
							 "Move the hinge cabinet up to the slide cabinet's position and the slide cabinet down to the hinge cabinet's position.",
							 "Change the positions of the slide cabinet and the hinge cabinet.",
							 "Replace the slide cabinet with the hinge cabinet and vice versa.",
							 "Exchange the positions of the hinge cabinet and the slide cabinet.",
							 "Swap the slide cabinet and the hinge cabinet."],
		"replace 3 with 5": ["Swap the positions of the slide cabinet and the microwave.",
							 "Move the slide cabinet to where the microwave is and move the microwave to where the slide cabinet is.",
							 "Put the microwave where the slide cabinet is and vice versa.",
							 "Rearrange the slide cabinet and the microwave.",
							 "Switch the microwave with the slide cabinet.",
							 "Place the microwave where the slide cabinet is and put the slide cabinet where the microwave is.",
							 "Interchange the slide cabinet and the microwave.",
							 "Move the microwave up to the slide cabinet's position and the slide cabinet down to the microwave's position.",
							 "Change the positions of the slide cabinet and the microwave.",
							 "Replace the slide cabinet with the microwave and vice versa.",
							 "Exchange the positions of the microwave and the slide cabinet."],
		"replace 3 with 6": ["Swap the positions of the slide cabinet and the kettle.",
							 "Move the slide cabinet to where the kettle is and move the kettle to where the slide cabinet is.",
							 "Put the kettle where the slide cabinet is and vice versa.",
							 "Rearrange the slide cabinet and the kettle.", "Switch the kettle with the slide cabinet.",
							 "Place the kettle where the slide cabinet is and put the slide cabinet where the kettle is.",
							 "Interchange the slide cabinet and the kettle.",
							 "Move the kettle up to the slide cabinet's position and the slide cabinet down to the kettle's position.",
							 "Change the positions of the slide cabinet and the kettle.",
							 "Replace the slide cabinet with the kettle and vice versa.",
							 "Exchange the positions of the kettle and the slide cabinet.",
							 "Swap the slide cabinet and the kettle."],
		"replace 4 with 0": [
			'Swap the positions of the hinge cabinet and the bottom burner.',
			'Move the hinge cabinet to where the bottom burner is and move the bottom burner to where the hinge cabinet is.',
			'Put the bottom burner where the hinge cabinet is and vice versa.',
			'Rearrange the hinge cabinet and the bottom burner.',
			'Switch the bottom burner with the hinge cabinet.',
			'Place the bottom burner where the hinge cabinet is and put the hinge cabinet where the bottom burner is.',
			'Interchange the hinge cabinet and the bottom burner.',
			'Move the bottom burner up to the hinge cabinets position and the hinge cabinet down to the bottom burners position.',
			'Change the positions of the hinge cabinet and the bottom burner.',
			'Replace the hinge cabinet with the bottom burner and vice versa.',
			'Exchange the positions of the bottom burner and the hinge cabinet.',
			'Swap the hinge cabinet and the bottom burner.'
		],
		"replace 4 with 1": ["Swap the positions of the hinge cabinet and the top burner.",
							 "Move the hinge cabinet to where the top burner is and move the top burner to where the hinge cabinet is.",
							 "Put the top burner where the hinge cabinet is and vice versa.",
							 "Rearrange the hinge cabinet and the top burner.",
							 "Switch the top burner with the hinge cabinet.",
							 "Place the top burner where the hinge cabinet is and put the hinge cabinet where the top burner is.",
							 "Interchange the hinge cabinet and the top burner.",
							 "Move the top burner down to the hinge cabinet's position and the hinge cabinet up to the top burner's position.",
							 "Change the positions of the hinge cabinet and the top burner.",
							 "Replace the hinge cabinet with the top burner and vice versa.",
							 "Exchange the positions of the top burner and the hinge cabinet.",
							 "Swap the hinge cabinet and the top burner."],
		"replace 4 with 2": ['Swap the positions of the hinge cabinet and the light switch.',
							 'Move the hinge cabinet to where the light switch is and move the light switch to where the hinge cabinet is.',
							 'Put the light switch where the hinge cabinet is and vice versa.',
							 'Rearrange the hinge cabinet and the light switch.',
							 'Switch the light switch with the hinge cabinet.',
							 'Place the light switch where the hinge cabinet is and put the hinge cabinet where the light switch is.',
							 'Interchange the hinge cabinet and the light switch.',
							 'Move the light switch down to the hinge cabinet\'s position and the hinge cabinet up to the light switch\'s position.',
							 'Change the positions of the hinge cabinet and the light switch.',
							 'Replace the hinge cabinet with the light switch and vice versa.',
							 'Exchange the positions of the light switch and the hinge cabinet.',
							 'Swap the hinge cabinet and the light switch.'],
		"replace 4 with 3": ["Swap the positions of the hinge cabinet and the slide cabinet.",
							 "Move the hinge cabinet to where the slide cabinet is and move the slide cabinet to where the hinge cabinet is.",
							 "Put the slide cabinet where the hinge cabinet is and vice versa.",
							 "Rearrange the hinge cabinet and the slide cabinet.",
							 "Switch the slide cabinet with the hinge cabinet.",
							 "Place the slide cabinet where the hinge cabinet is and put the hinge cabinet where the slide cabinet is.",
							 "Interchange the hinge cabinet and the slide cabinet.",
							 "Move the slide cabinet up to the hinge cabinet's position and the hinge cabinet down to the slide cabinet's position.",
							 "Change the positions of the hinge cabinet and the slide cabinet.",
							 "Replace the hinge cabinet with the slide cabinet and vice versa.",
							 "Exchange the positions of the slide cabinet and the hinge cabinet.",
							 "Swap the hinge cabinet and the slide cabinet."],
		"replace 4 with 5": ["Swap the positions of the hinge cabinet and the microwave.",
							 "Move the hinge cabinet to where the microwave is and move the microwave to where the hinge cabinet is.",
							 "Put the microwave where the hinge cabinet is and vice versa.",
							 "Rearrange the hinge cabinet and the microwave.",
							 "Switch the microwave with the hinge cabinet.",
							 "Place the microwave where the hinge cabinet is and put the hinge cabinet where the microwave is.",
							 "Interchange the hinge cabinet and the microwave.",
							 "Move the microwave up to the hinge cabinet's position and the hinge cabinet down to the microwave's position.",
							 "Change the positions of the hinge cabinet and the microwave.",
							 "Replace the hinge cabinet with the microwave and vice versa.",
							 "Exchange the positions of the microwave and the hinge cabinet.",
							 "Swap the hinge cabinet and the microwave."],
		"replace 4 with 6": ['Swap the positions of the hinge cabinet and the kettle.',
							 'Move the hinge cabinet to where the kettle is and move the kettle to where the hinge cabinet is.',
							 'Put the kettle where the hinge cabinet is and vice versa.',
							 'Rearrange the hinge cabinet and the kettle.',
							 'Switch the kettle with the hinge cabinet.',
							 'Place the kettle where the hinge cabinet is and put the hinge cabinet where the kettle is.',
							 'Interchange the hinge cabinet and the kettle.',
							 'Move the kettle up to the hinge cabinet\'s position and the hinge cabinet down to the kettle\'s position.',
							 'Change the positions of the hinge cabinet and the kettle.',
							 'Replace the hinge cabinet with the kettle and vice versa.',
							 'Exchange the positions of the kettle and the hinge cabinet.',
							 'Swap the hinge cabinet and the kettle.'],
		"replace 5 with 0": [
			"Substitute bottom burner for microwave.",
			"Exchange bottom burner and microwave.",
			"Swap the positions of the microwave and bottom burner.",
			"Put the bottom burner where the microwave is and remove the microwave.",
			"Move the microwave and install a bottom burner in its place.",
			"Switch out the microwave for a bottom burner.",
			"Replace the microwave with a bottom burner.",
			"Trade the microwave for a bottom burner.",
			"Remove the microwave and put a bottom burner in its place.",
			"Swap out the microwave with a bottom burner."
		],
		"replace 5 with 1": [
			"Exchange the microwave with the top burner",
			"Swap the microwave and the top burner",
			"Replace the microwave with the top burner and vice versa",
			"Put the top burner where the microwave is and move the microwave to where the top burner is",
			"Move the top burner to where the microwave is and put the microwave where the top burner is",
			"Switch the positions of the microwave and the top burner",
			"Rearrange the microwave and the top burner",
			"Interchange the microwave and the top burner",
			"Change the positions of the microwave and the top burner",
			"Place the top burner where the microwave is and vice versa"
		],
		"replace 5 with 2": ["Swap the positions of the microwave and the light switch",
							 "Move the light switch where the microwave is and put the microwave where the light switch is",
							 "Exchange the microwave and the light switch",
							 "Replace the microwave with the light switch",
							 "Put the light switch in place of the microwave and vice versa",
							 "Rearrange the microwave and the light switch",
							 "Switch the microwave with the light switch",
							 "Move the light switch to the microwave's position and the microwave to the light switch's position",
							 "Place the light switch where the microwave is and put the microwave where the light switch is",
							 "Interchange the microwave and the light switch"],
		"replace 5 with 3": [
			"Swap microwave and slide cabinet",
			"Exchange microwave for slide cabinet",
			"Switch the positions of microwave and slide cabinet",
			"Put slide cabinet where microwave is and vice versa",
			"Move slide cabinet to microwave's position and vice versa",
			"Replace the microwave with the slide cabinet",
			"Interchange the microwave and slide cabinet",
			"Rearrange the microwave and slide cabinet",
			"Place slide cabinet where microwave is and put microwave where slide cabinet is",
			"Swap the microwave and slide cabinet"
		],
		"replace 5 with 4": ["Swap the microwave with the hinge cabinet",
							 "Exchange the microwave for the hinge cabinet",
							 "Switch the microwave with the hinge cabinet",
							 "Put the hinge cabinet where the microwave is and remove the microwave",
							 "Move the hinge cabinet to where the microwave is and take out the microwave",
							 "Replace the microwave by the hinge cabinet",
							 "Substitute the hinge cabinet for the microwave",
							 "Move the hinge cabinet up and the microwave down",
							 "Exchange the positions of the microwave and the hinge cabinet",
							 "Rearrange the microwave and the hinge cabinet"],
		"replace 5 with 6": ["Substitute kettle for microwave", "Swap out the microwave for the kettle",
							 "Replace the microwave with the kettle appliance", "Exchange the microwave for the kettle",
							 "Use the kettle instead of the microwave", "Trade the microwave for the kettle",
							 "Replace the microwave appliance with the kettle",
							 "Put the kettle in place of the microwave", "Switch the microwave for the kettle",
							 "Substitute the microwave with the kettle appliance"],
		"replace 6 with 0": ["Swap positions of kettle and bottom burner", "Exchange kettle and bottom burner",
							 "Move bottom burner where kettle is and put kettle where bottom burner is",
							 "Rearrange kettle and bottom burner",
							 "Replace kettle with bottom burner and move kettle to where bottom burner was",
							 "Put bottom burner where kettle is and move kettle to where bottom burner was",
							 "Interchange kettle and bottom burner", "Switch kettle with bottom burner",
							 "Move bottom burner to where kettle is and move kettle to where bottom burner is",
							 "Place bottom burner where kettle is and put kettle where bottom burner is"],
		"replace 6 with 1": ["Exchange the position of the kettle and the top burner",
							 "Move the top burner where the kettle is and put the kettle where the top burner is",
							 "Switch the kettle with the top burner",
							 "Put the top burner where the kettle is and move the kettle to where the top burner is",
							 "Replace the kettle with the top burner and vice versa",
							 "Swap the positions of the kettle and the top burner",
							 "Interchange the kettle and the top burner",
							 "Change the positions of the kettle and the top burner",
							 "Move the top burner down to the kettle's position and the kettle up to the top burner's position",
							 "Rearrange the kettle and the top burner"],
		"replace 6 with 2": ["Swap kettle with light switch", "Switch light switch with kettle",
							 "Exchange light switch and kettle",
							 "Move light switch where kettle is and move kettle where light switch is",
							 "Put light switch in place of kettle and vice versa",
							 "Replace the kettle with the light switch", "Rearrange the light switch and kettle",
							 "Interchange the kettle and light switch",
							 "Change the position of the kettle and put the light switch there instead",
							 "Substitute the kettle for the light switch"],
		"replace 6 with 3": ["Swap kettle with slide cabinet",
							 "Move slide cabinet where the kettle is and move the kettle where the slide cabinet is",
							 "Put slide cabinet where kettle is and put kettle where slide cabinet is",
							 "Switch slide cabinet with kettle",
							 "Place slide cabinet where kettle is and put kettle where slide cabinet is",
							 "Interchange slide cabinet and kettle",
							 "Move kettle up to slide cabinet's position and slide cabinet down to kettle's position",
							 "Change positions of slide cabinet and kettle",
							 "Replace kettle with slide cabinet and vice versa",
							 "Exchange positions of slide cabinet and kettle"],
		"replace 6 with 4": ["Swap the positions of the kettle and the hinge cabinet.",
							 "Move the hinge cabinet to where the kettle is and move the kettle to where the hinge cabinet is.",
							 "Put the hinge cabinet where the kettle is and vice versa.",
							 "Rearrange the kettle and the hinge cabinet.", "Switch the hinge cabinet with the kettle.",
							 "Place the hinge cabinet where the kettle is and put the kettle where the hinge cabinet is.",
							 "Interchange the kettle and the hinge cabinet.",
							 "Move the hinge cabinet up to the kettle's position and the kettle down to the hinge cabinet's position.",
							 "Change the positions of the kettle and the hinge cabinet.",
							 "Replace the kettle with the hinge cabinet and vice versa."],
		"replace 6 with 5": [
			"Exchange the positions of the kettle and the microwave.",
			"Swap the kettle and the microwave.",
			"Put the microwave where the kettle is and move the kettle to where the microwave is.",
			"Move the microwave to where the kettle is and put the kettle where the microwave is.",
			"Replace the kettle with the microwave and vice versa.",
			"Switch the microwave with the kettle.",
			"Interchange the kettle and the microwave.",
			"Rearrange the kettle and the microwave.",
			"Move the microwave up to the kettle's position and the kettle down to the microwave's position.",
			"Change the positions of the kettle and the microwave."
		]
	}
	assert main_texts == list(texts_variations.keys())

	# === Hyper parameters

	tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
	model = BertModel.from_pretrained("bert-base-uncased").cuda()

	save_dict = {main_text: dict() for main_text in main_texts}

	time = 0
	with th.no_grad():
		for key, variations in texts_variations.items():
			for text in variations:
				time += 1
				encoded_input = tokenizer(text, return_tensors='pt').to("cuda:0")
				output = model(**encoded_input)["last_hidden_state"]
				sentence_vector = th.mean(output, dim=1).squeeze()
				sentence_vector = sentence_vector.cpu().numpy()
				save_dict[key][text] = sentence_vector

	with open(Path(save_dir) / Path(f"{topic}_bert_base_mapping"), "wb") as f:
		pickle.dump(save_dict, f)
